export type PracticeCategory = "职场工作" | "饮食文化" | "交通与社交" | "生活情绪" | "地道口语";

export type PracticeVocab = {
  id: string;
  category: PracticeCategory;
  canto: string;
  mandarin: string;
  jyutping: string;
  sentence: string;
  sentence_jyutping: string;
  sentence_mandarin: string;
  sentence_pinyin: string;
};

type RawEntry = [canto: string, mandarin: string, jyutping: string];
type RawSentenceEntry = [canto: string, mandarin: string, jyutping: string, sentence: string, sentence_pinyin: string];

const WORK_RAW: RawEntry[] = [
  ["开会", "开会", "hoi1 wui6"], ["散会", "散会", "saan3 wui6"], ["会议", "会议", "wui6 ji5"], ["议程", "议程", "ji5 cing4"],
  ["主持", "主持", "zyu2 ci4"], ["记录", "记录", "gei3 luk6"], ["跟进", "跟进", "gan1 zeon3"], ["汇报", "汇报", "wui6 bou3"],
  ["报告", "报告", "bou3 gou3"], ["写报告", "写报告", "se2 bou3 gou3"], ["简报", "简报", "gaan2 bou3"], ["计划", "计划", "gai3 waak6"],
  ["方案", "方案", "fong1 on3"], ["预算", "预算", "jyu5 syun3"], ["审批", "审批", "sam1 pai3"], ["批核", "批核", "pai1 hat6"],
  ["签名", "签名", "cim1 meng2"], ["签文件", "签文件", "cim1 man4 gin2"], ["文件", "文件", "man4 gin2"], ["档案", "档案", "dong3 on2"],
  ["合约", "合同", "hap6 joek3"], ["条款", "条款", "tiu4 fun2"], ["报价", "报价", "bou3 gaa3"], ["议价", "议价", "ji5 gaa3"],
  ["投标", "投标", "tau4 biu1"], ["中标", "中标", "zung3 biu1"], ["成本", "成本", "sing4 bun2"], ["利润", "利润", "lei6 jeon6"],
  ["业绩", "业绩", "jip6 zik1"], ["指标", "指标", "zi2 biu1"], ["目标", "目标", "muk6 biu1"], ["表现", "表现", "biu2 jin6"],
  ["效率", "效率", "haau6 leot6"], ["流程", "流程", "lau4 cing4"], ["系统", "系统", "hai6 tung2"], ["权限", "权限", "kyun4 han6"],
  ["账号", "账号", "zoeng3 hou6"], ["密码", "密码", "bei3 maa5"], ["登入", "登录", "dang1 jap6"], ["登出", "登出", "dang1 ceot1"],
  ["上传", "上传", "soeng6 cyun4"], ["下载", "下载", "haa6 zoi6"], ["更新", "更新", "gang1 san1"], ["保存", "保存", "bou2 cyun4"],
  ["删除", "删除", "saat3 ceoi4"], ["复制", "复制", "fuk1 zai3"], ["粘贴", "粘贴", "zim1 tip3"], ["打印", "打印", "daai2 jan3"],
  ["扫描", "扫描", "sou3 miu4"], ["邮件", "邮件", "jau6 gin2"], ["发邮件", "发邮件", "faat3 jau6 gin2"], ["电邮", "电邮", "din6 jau4"],
  ["收件箱", "收件箱", "sau1 gin6 soeng1"], ["抄送", "抄送", "caau1 sung3"], ["附件", "附件", "fu6 gin2"], ["主题", "主题", "zyu6 tai4"],
  ["回复", "回复", "wui4 fuk1"], ["转发", "转发", "zyun2 faat3"], ["截止", "截止", "zit3 zi2"], ["限期", "期限", "haan6 kei4"],
  ["排期", "排期", "paai4 kei4"], ["日程", "日程", "jat6 cing4"], ["日历", "日历", "jat6 lik6"], ["提醒", "提醒", "tai4 sing2"],
  ["预约", "预约", "jyu6 joek3"], ["客户", "客户", "haak3 wu6"], ["客人", "客人", "haak3 jan4"], ["同事", "同事", "tung4 si6"],
  ["拍档", "搭档", "paak3 dong3"], ["团队", "团队", "tyun4 deoi6"], ["部门", "部门", "bou6 mun4"], ["人事", "人事", "jan4 si6"],
  ["行政", "行政", "hang4 zing3"], ["财务", "财务", "coi4 mou6"], ["市场", "市场", "si5 coeng4"], ["销售", "销售", "sau2 siu3"],
  ["采购", "采购", "caai2 gau3"], ["仓库", "仓库", "cong1 fu3"], ["物流", "物流", "mat6 lau4"], ["供应", "供应", "gung1 jing3"],
  ["供应商", "供应商", "gung1 jing3 soeng1"], ["老板", "老板", "lou5 baan2"], ["大佬", "上司", "daai6 lou2"], ["上司", "上司", "soeng6 si1"],
  ["经理", "经理", "ging2 lei5"], ["总监", "总监", "zung2 gaam1"], ["秘书", "秘书", "bei3 syu1"], ["前台", "前台", "cin4 toi4"],
  ["写字楼", "办公楼", "se2 zi6 lau4"], ["工位", "工位", "gung1 wai6"], ["会议室", "会议室", "wui6 ji5 sat1"], ["茶水间", "茶水间", "caa4 seoi2 gaan1"],
  ["打卡", "打卡", "daa2 kaat1"], ["加班", "加班", "gaa1 baan1"], ["放工", "下班", "fong3 gung1"], ["请假", "请假", "ceng2 gaa3"],
  ["补假", "补假", "bou2 gaa3"], ["病假", "病假", "beng6 gaa3"], ["迟到", "迟到", "ci4 dou3"], ["早退", "早退", "zou2 teoi3"],
  ["出差", "出差", "ceot1 caai1"], ["见客", "见客户", "gin3 haak3"], ["培训", "培训", "pui4 fan3"], ["实习", "实习", "sat6 zaap6"],
  ["试用期", "试用期", "si3 jung6 kei4"], ["转正", "转正", "zyun2 zing3"], ["升职", "升职", "sing1 zik1"], ["加薪", "加薪", "gaa1 san1"],
  ["人工", "工资", "jan4 gung1"], ["奖金", "奖金", "zoeng2 gam1"], ["福利", "福利", "fuk1 lei6"], ["强积金", "强积金", "koeng4 zik1 gam1"],
  ["离职", "离职", "lei4 zik1"], ["辞职", "辞职", "ci4 zik1"], ["交接", "交接", "gaau1 zip3"], ["远程办公", "远程办公", "jyun5 cing4 baan1 gung1"],
  ["喺屋企办公", "在家办公", "hai2 uk1 kei2 baan1 gung1"], ["开OT", "加班", "hoi1 ou1 ti1"], ["赶deadline", "赶截止日期", "gon2 ded1 lai1"], ["写proposal", "写方案", "se2 propou1 sou3"],
];

const FOOD_RAW: RawEntry[] = [
  ["饮茶", "喝茶/吃点心", "jam2 caa4"], ["食饭", "吃饭", "sik6 faan6"], ["食晏", "吃午饭", "sik6 aan3"], ["食宵夜", "吃夜宵", "sik6 siu1 je6"],
  ["点心", "点心", "dim2 sam1"], ["虾饺", "虾饺", "haa1 gaau2"], ["烧卖", "烧卖", "siu1 maai6"], ["肠粉", "肠粉", "coeng4 fan2"],
  ["叉烧包", "叉烧包", "caa1 siu1 baau1"], ["奶茶", "奶茶", "naai5 caa4"], ["冻柠茶", "冰柠茶", "dung3 ning4 caa4"], ["鸳鸯", "鸳鸯奶茶", "jyun1 joeng1"],
  ["咖啡", "咖啡", "gaa3 fe1"], ["菠萝包", "菠萝包", "bo1 lo4 baau1"], ["蛋挞", "蛋挞", "daan6 taat1"], ["西多士", "法兰西多士", "sai1 do1 si6"],
  ["茶餐厅", "茶餐厅", "caa4 caan1 teng1"], ["卡位", "卡座", "kaa1 wai2"], ["落单", "下单", "lok6 daan1"], ["等位", "等位", "dang2 wai2"],
  ["埋单", "买单", "maai4 daan1"], ["AA制", "AA制", "ei1 ei1 zai3"], ["打包", "打包", "daa2 baau1"], ["外卖", "外卖", "ngoi6 maai6"],
  ["堂食", "堂食", "tong4 sik6"], ["走糖", "少糖", "zau2 tong4"], ["走冰", "去冰", "zau2 bing1"], ["少甜", "少甜", "siu2 tim4"],
  ["少冰", "少冰", "siu2 bing1"], ["热饮", "热饮", "jit6 jam2"], ["冻饮", "冷饮", "dung3 jam2"], ["加料", "加配料", "gaa1 liu2"],
  ["加底", "加底料", "gaa1 dai2"], ["加饭", "加饭", "gaa1 faan6"], ["加钱", "加钱", "gaa1 cin2"], ["例汤", "例汤", "lai6 tong1"],
  ["靓汤", "好喝的汤", "leng3 tong1"], ["白饭", "白米饭", "baak6 faan6"], ["炒饭", "炒饭", "caau2 faan6"], ["炒面", "炒面", "caau2 min6"],
  ["河粉", "河粉", "ho4 fan2"], ["米线", "米线", "mai5 sin3"], ["云吞", "馄饨", "wan4 tan1"], ["牛腩", "牛腩", "ngau4 naam5"],
  ["叉烧", "叉烧", "caa1 siu1"], ["烧鹅", "烧鹅", "siu1 ngo4"], ["白切鸡", "白切鸡", "baak6 cit3 gai1"], ["猪扒", "猪排", "zyu1 paa4"],
  ["鱼蛋", "鱼丸", "jyu4 daan2"], ["车仔面", "车仔面", "ce1 zai2 min6"], ["粥底", "粥底", "zuk1 dai2"], ["火锅", "火锅", "fo2 wo1"],
  ["甜品", "甜品", "tim4 ban2"], ["糖水", "糖水", "tong4 seoi2"], ["芝士", "芝士", "zi1 si2"], ["酱料", "酱料", "zoeng3 liu2"],
  ["胡椒", "胡椒", "wu4 ziu1"], ["辣椒", "辣椒", "laat6 ziu1"], ["筷子", "筷子", "faai3 zi2"], ["冻柠乐", "冰柠可乐", "dung3 ning4 lok6"],
];

const SOCIAL_RAW: RawEntry[] = [
  ["飞的", "打车", "fei1 dik1"], ["的士", "出租车", "dik1 si2"], ["巴士", "公交车", "baa1 si2"], ["小巴", "小巴", "siu2 baa1"],
  ["地铁", "地铁", "dei6 tit3"], ["港铁", "港铁", "gong2 tit3"], ["火车", "火车", "fo2 ce1"], ["高铁", "高铁", "gou1 tit3"],
  ["渡轮", "轮渡", "dou6 leon4"], ["电车", "电车", "din6 ce1"], ["单车", "自行车", "daan1 ce1"], ["私家车", "私家车", "si1 gaa1 ce1"],
  ["塞车", "堵车", "sak1 ce1"], ["过海", "过海", "gwo3 hoi2"], ["转车", "换乘", "zyun2 ce1"], ["落车", "下车", "lok6 ce1"],
  ["上车", "上车", "soeng5 ce1"], ["拍卡", "刷卡", "paak3 kaat1"], ["八达通", "八达通", "baat3 daat6 tung1"], ["月票", "月票", "jyut6 piu3"],
  ["车费", "车费", "ce1 fai3"], ["车站", "车站", "ce1 zaam6"], ["站头", "站点", "zaam6 tau4"], ["红绿灯", "红绿灯", "hung4 luk6 dang1"],
  ["斑马线", "斑马线", "baan1 maa5 sin3"], ["行人路", "人行道", "haang4 jan4 lou6"], ["行街", "逛街", "haang4 gaai1"], ["睇戏", "看电影", "tai2 hei3"],
  ["睇波", "看球赛", "tai2 bo1"], ["唱K", "唱K", "coeng3 kei1"], ["打机", "打游戏", "daa2 gei1"], ["饮嘢", "喝东西", "jam2 je5"],
  ["约人", "约人", "joek3 jan4"], ["搵人", "找人", "wan2 jan4"], ["接人", "接人", "zip3 jan4"], ["放飞机", "放鸽子", "fong3 fei1 gei1"],
  ["准时", "准时", "zeon2 si4"], ["见面", "见面", "gin3 min6"], ["倾计", "聊天", "king1 gai3"], ["吹水", "闲聊", "ceoi1 seoi2"],
  ["自拍", "自拍", "zi6 paak3"], ["群组", "群组", "kwan4 zou2"], ["加好友", "加好友", "gaa1 hou2 jau5"], ["私讯", "私信", "si1 seon3"],
  ["点赞", "点赞", "dim2 zaan3"], ["留言", "留言", "lau4 jin4"], ["约饭", "约吃饭", "joek3 faan6"], ["约会", "约会", "joek3 wui2"],
  ["散步", "散步", "saan3 bou6"], ["跑步", "跑步", "paau2 bou6"], ["郊游", "郊游", "gaau1 jau4"], ["睇展", "看展览", "tai2 zin2"],
  ["睇演唱会", "看演唱会", "tai2 jin2 coeng3 wui2"], ["夜蒲", "夜生活", "je6 pou4"], ["返屋企", "回家", "faan1 uk1 kei2"], ["过嚟", "过来", "gwo3 lai4"],
  ["搭顺风车", "搭顺风车", "daap3 seon6 fung1 ce1"], ["过马路", "过马路", "gwo3 maa5 lou6"], ["转线", "转线", "zyun2 sin3"], ["等车", "等车", "dang2 ce1"],
];

const EMOTION_RAW: RawEntry[] = [
  ["开心", "开心", "hoi1 sam1"], ["唔开心", "不开心", "m4 hoi1 sam1"], ["激气", "生气", "gik1 hei3"], ["烦躁", "烦躁", "faan4 cou3"],
  ["好犀利", "很厉害", "hou2 sai1 lei6"], ["紧张", "紧张", "gan2 zoeng1"], ["放松", "放松", "fong3 sung1"], ["担心", "担心", "daam1 sam1"],
  ["放心", "放心", "fong3 sam1"], ["惊", "害怕", "geng1"], ["惊青", "慌张", "geng1 ceng1"], ["嬲", "生气", "nau1"],
  ["无奈", "无奈", "mou4 noi6"], ["尴尬", "尴尬", "gaam3 gaai3"], ["失望", "失望", "sat1 mong6"], ["感动", "感动", "gam2 dung6"],
  ["满足", "满足", "mun5 zuk1"], ["幸福", "幸福", "hang6 fuk1"], ["感激", "感激", "gam2 gik1"], ["内疚", "内疚", "noi6 gau3"],
  ["后悔", "后悔", "hau6 fui3"], ["自豪", "自豪", "zi6 hou4"], ["压力", "压力", "aat3 lik6"], ["崩溃", "崩溃", "bang1 kui2"],
  ["冷静", "冷静", "laang5 zing6"], ["冲动", "冲动", "cung1 dung6"], ["厌烦", "厌烦", "jim3 faan4"], ["期待", "期待", "kei4 doi6"],
  ["兴奋", "兴奋", "hing1 fan5"], ["专心", "专心", "zyun1 sam1"], ["分心", "分心", "fan1 sam1"], ["无聊", "无聊", "mou4 liu4"],
  ["闷", "闷", "mun6"], ["精神", "精神", "zing1 san4"], ["疲倦", "疲倦", "pei4 gyun6"], ["眼瞓", "困", "ngaan5 fan3"],
  ["肚饿", "肚子饿", "tou5 ngo6"], ["口渴", "口渴", "hau2 hot3"], ["心急", "着急", "sam1 gap1"], ["淡定", "淡定", "daam6 ding6"],
  ["挣扎", "挣扎", "zang1 zaat3"], ["感慨", "感慨", "gam2 koi2"], ["疑惑", "疑惑", "ji4 waak6"], ["佩服", "佩服", "pui3 fuk6"],
  ["妒忌", "嫉妒", "dou3 gei6"], ["羞愧", "羞愧", "sau1 kwai5"], ["安心", "安心", "on1 sam1"], ["激动", "激动", "gik1 dung6"],
  ["火滚", "火大", "fo2 gwan2"], ["冇瘾", "没劲", "mou5 jan2"], ["上心", "上心", "soeng5 sam1"], ["灰心", "灰心", "fui1 sam1"],
  ["有信心", "有信心", "jau5 seon3 sam1"], ["乐观", "乐观", "lok6 gun1"], ["悲观", "悲观", "bei1 gun1"], ["无助", "无助", "mou4 zo6"],
  ["释怀", "释怀", "sik1 waai4"], ["舒服", "舒服", "syu1 fuk6"], ["唔舒服", "不舒服", "m4 syu1 fuk6"], ["治愈", "治愈", "zi6 jyu6"],
];

const FOOD_HK_EXTRA_RAW: RawSentenceEntry[] = [
  ["埋单", "买单", "maai4 daan1", "唔该，呢边埋单。", "m4 goi1, ni1 bin1 maai4 daan1."],
  ["加餸", "加菜", "gaa1 sung3", "今日加餸，有蒸鱼。", "gam1 jat6 gaa1 sung3, jau5 zing1 jyu4."],
  ["行拍", "快火翻热", "haang4 paak3", "呢碟帮我行拍一下先。", "ni1 dip6 bong1 ngo5 haang4 paak3 jat1 haa5 sin1."],
  ["走青", "不要葱", "zau2 ceng1", "我要碗河粉走青。", "ngo5 jiu3 wun2 ho4 fan2 zau2 ceng1."],
  ["細蓉", "小碗云吞面", "sai3 jung4", "朝早食碗細蓉就够。", "ziu1 zou2 sik6 wun2 sai3 jung4 zau6 gau3."],
  ["烘底", "面包烘脆底部", "hung3 dai2", "多士记得烘底啊。", "do1 si2 gei3 dak1 hung3 dai2 aa3."],
  ["打冷", "潮州卤味摊", "daa2 laang5", "今晚去打冷食夜宵。", "gam1 maan5 heoi3 daa2 laang5 sik6 je6 siu1."],
  ["两餸饭", "两菜一饭", "loeng5 sung3 faan6", "楼下两餸饭平又快。", "lau4 haa6 loeng5 sung3 faan6 peng4 jau6 faai3."],
  ["茶记", "茶餐厅", "caa4 gei3", "我哋喺茶记等你。", "ngo5 dei6 hai2 caa4 gei3 dang2 nei5."],
  ["飞沙走奶", "奶茶少奶", "fei1 saa1 zau2 naai5", "我要杯飞沙走奶。", "ngo5 jiu3 bui1 fei1 saa1 zau2 naai5."],
  ["凍柠茶", "冰柠茶", "dung3 ning4 caa4", "天气热，饮凍柠茶最啱。", "tin1 hei3 jit6, jam2 dung3 ning4 caa4 zeoi3 ngaam1."],
  ["凍柠乐", "冰柠可乐", "dung3 ning4 lok6", "佢最钟意凍柠乐。", "keoi5 zeoi3 zung1 ji3 dung3 ning4 lok6."],
  ["凍鸳鸯", "冰鸳鸯", "dung3 jyun1 joeng1", "午餐我饮凍鸳鸯。", "ng5 caan1 ngo5 jam2 dung3 jyun1 joeng1."],
  ["热鸳鸯", "热鸳鸯", "jit6 jyun1 joeng1", "落雨天饮热鸳鸯好舒服。", "lok6 jyu5 tin1 jam2 jit6 jyun1 joeng1 hou2 syu1 fuk6."],
  ["奶酱多", "奶油炼乳多士", "naai5 zoeng3 do1", "奶酱多要趁热食。", "naai5 zoeng3 do1 jiu3 can3 jit6 sik6."],
  ["蛋治", "鸡蛋三明治", "daan6 zi6", "早餐来份蛋治先。", "zou2 caan1 loi4 fan6 daan6 zi6 sin1."],
  ["腿蛋治", "火腿鸡蛋三明治", "teoi2 daan6 zi6", "我点咗份腿蛋治。", "ngo5 dim2 zo2 fan6 teoi2 daan6 zi6."],
  ["餐蛋麵", "午餐肉鸡蛋面", "caan1 daan6 min6", "宵夜食餐蛋麵最方便。", "siu1 je6 sik6 caan1 daan6 min6 zeoi3 fong1 bin6."],
  ["沙嗲牛肉麵", "沙爹牛肉面", "saa1 de1 ngau4 juk6 min6", "茶记啲沙嗲牛肉麵几出名。", "caa4 gei3 di1 saa1 de1 ngau4 juk6 min6 gei2 ceot1 ming4."],
  ["乾炒牛河", "干炒牛河", "gon1 caau2 ngau4 ho4", "呢间铺嘅乾炒牛河好有镬气。", "ni1 gaan1 pou3 ge3 gon1 caau2 ngau4 ho4 hou2 jau5 wok6 hei3."],
  ["豉油皇炒麵", "豉油皇炒面", "si6 jau4 wong4 caau2 min6", "豉油皇炒麵够香口。", "si6 jau4 wong4 caau2 min6 gau3 hoeng1 hau2."],
  ["艇仔粥", "艇仔粥", "teng5 zai2 zuk1", "朝早食艇仔粥暖胃。", "ziu1 zou2 sik6 teng5 zai2 zuk1 nyun5 wai6."],
  ["及第粥", "及第粥", "kap6 dai6 zuk1", "阿爸最钟意及第粥。", "aa3 baa4 zeoi3 zung1 ji3 kap6 dai6 zuk1."],
  ["例汤", "例汤", "lai6 tong1", "今日例汤係老火汤。", "gam1 jat6 lai6 tong1 hai6 lou5 fo2 tong1."],
  ["老火汤", "老火汤", "lou5 fo2 tong1", "阿妈煲嘅老火汤好甜。", "aa3 maa1 bou1 ge3 lou5 fo2 tong1 hou2 tim4."],
  ["白灼菜", "白灼青菜", "baak6 zoek3 coi3", "食饭要叫碟白灼菜。", "sik6 faan6 jiu3 giu3 dip6 baak6 zoek3 coi3."],
  ["椒盐鲜鱿", "椒盐鲜鱿", "ziu1 jim4 sin1 jau4", "今晚食椒盐鲜鱿。", "gam1 maan5 sik6 ziu1 jim4 sin1 jau4."],
  ["避风塘炒蟹", "避风塘炒蟹", "bei6 fung1 tong4 caau2 haai5", "佢哋最拿手係避风塘炒蟹。", "keoi5 dei6 zeoi3 naa4 sau2 hai6 bei6 fung1 tong4 caau2 haai5."],
  ["煲仔饭", "煲仔饭", "bou1 zai2 faan6", "冬天食煲仔饭最正。", "dung1 tin1 sik6 bou1 zai2 faan6 zeoi3 zeng3."],
  ["糖不甩", "糯米甜点", "tong4 bat1 lat1", "饭后食件糖不甩。", "faan6 hau6 sik6 gin6 tong4 bat1 lat1."],
];

const COLLOQ_EXTRA_RAW: RawSentenceEntry[] = [
  ["收皮", "闭嘴/收手", "sau1 pei4", "你再嘈就收皮啦。", "nei5 zoi3 cou4 zau6 sau1 pei4 laa1."],
  ["灰咗", "泄气了", "fui1 zo2", "听到个消息我即刻灰咗。", "teng1 dou2 go3 siu1 sik1 ngo5 zik1 hak1 fui1 zo2."],
  ["无厘头", "莫名其妙", "mou4 lei4 tau4", "佢讲嘢成日都好无厘头。", "keoi5 gong2 je5 seng4 jat6 dou1 hou2 mou4 lei4 tau4."],
  ["大镬", "糟糕了", "daai6 wok6", "今次真係大镬喇。", "gam1 ci3 zan1 hai6 daai6 wok6 laa3."],
  ["搞掂", "搞定", "gaau2 dim6", "份文件我搞掂咗。", "fan6 man4 gin2 ngo5 gaau2 dim6 zo2."],
  ["离谱", "夸张过分", "lei4 pou2", "呢个价钱真係离谱。", "ni1 go3 gaa3 cin4 zan1 hai6 lei4 pou2."],
  ["痴线", "神经病/离谱", "ci1 sin3", "你讲乜咁痴线㗎。", "nei5 gong2 mat1 gam3 ci1 sin3 gaa3."],
  ["冇眼睇", "看不下去", "mou5 ngaan5 tai2", "呢场波踢到我冇眼睇。", "ni1 coeng4 bo1 tek3 dou3 ngo5 mou5 ngaan5 tai2."],
  ["唔掂", "不行", "m4 dim6", "部机仲係唔掂。", "bou6 gei1 zung6 hai6 m4 dim6."],
  ["掂过碌蔗", "非常顺利", "dim6 gwo3 luk1 ze3", "今日做嘢掂过碌蔗。", "gam1 jat6 zou6 je5 dim6 gwo3 luk1 ze3."],
  ["是但", "随便", "si6 daan6", "食乜都得，係但啦。", "sik6 mat1 dou1 dak1, hai6 daan6 laa1."],
  ["求其", "随意", "kau4 kei4", "佢做嘢太求其。", "keoi5 zou6 je5 taai3 kau4 kei4."],
  ["咩料", "什么情况", "me1 liu2", "你哋而家咩料啊？", "nei5 dei6 ji4 gaa1 me1 liu2 aa3?"],
  ["做乜", "干嘛", "zou6 mat1", "你做乜咁夜都唔瞓？", "nei5 zou6 mat1 gam3 je6 dou1 m4 fan3?"],
  ["乜嘢", "什么", "mat1 je5", "你想食乜嘢？", "nei5 soeng2 sik6 mat1 je5?"],
  ["唔係嘛", "不是吧", "m4 hai6 maa3", "唔係嘛，咁都得？", "m4 hai6 maa3, gam3 dou1 dak1?"],
  ["吓亲", "吓到", "haak1 can1", "你头先真係吓亲我。", "nei5 tau4 sin1 zan1 hai6 haak1 can1 ngo5."],
  ["顶唔顺", "受不了", "ding2 m4 seon6", "呢个天气热到我顶唔顺。", "ni1 go3 tin1 hei3 jit6 dou3 ngo5 ding2 m4 seon6."],
  ["好鬼正", "特别棒", "hou2 gwai2 zeng3", "呢间铺啲烧味好鬼正。", "ni1 gaan1 pou3 di1 siu1 mei6 hou2 gwai2 zeng3."],
  ["冇瘾", "没意思", "mou5 jan2", "成晚都坐喺度，好冇瘾。", "seng4 maan5 dou1 co5 hai2 dou6, hou2 mou5 jan2."],
  ["唔争在", "不差这点", "m4 zang1 zoi6", "都做到咁，不如唔争在做埋。", "dou1 zou6 dou3 gam3, bat1 jyu4 m4 zang1 zoi6 zou6 maai4."],
  ["冇所谓", "无所谓", "mou5 so2 wai6", "我冇所谓，你决定啦。", "ngo5 mou5 so2 wai6, nei5 kyut3 ding6 laa1."],
  ["火滚", "火大", "fo2 gwan2", "佢讲到我好火滚。", "keoi5 gong2 dou3 ngo5 hou2 fo2 gwan2."],
  ["激死", "气死", "gik1 sei2", "真係激死我喇。", "zan1 hai6 gik1 sei2 ngo5 laa3."],
  ["懒醒", "自作聪明", "laan5 seng2", "唔好咁懒醒啦。", "m4 hou2 gam3 laan5 seng2 laa1."],
  ["扮晒嘢", "装模作样", "baan6 saai3 je5", "佢成日扮晒嘢。", "keoi5 seng4 jat6 baan6 saai3 je5."],
  ["食花生", "围观吃瓜", "sik6 faa1 sang1", "我哋坐定定食花生。", "ngo5 dei6 co5 deng6 deng6 sik6 faa1 sang1."],
  ["吹水", "闲聊", "ceoi1 seoi2", "放工一齐去吹水。", "fong3 gung1 jat1 cai4 heoi3 ceoi1 seoi2."],
  ["硬食", "硬着头皮接受", "ngaang6 sik6", "今次唯有硬食。", "gam1 ci3 wai4 jau5 ngaang6 sik6."],
  ["睇餸食饭", "看情况行事", "tai2 sung3 sik6 faan6", "你要睇餸食饭先得。", "nei5 jiu3 tai2 sung3 sik6 faan6 sin1 dak1."],
];

function makeCategoryEntries(
  raw: RawEntry[],
  category: PracticeCategory,
  prefix: string,
): PracticeVocab[] {
  const templatesByCategory: Record<
    PracticeCategory,
    Array<{ zh: (word: string) => string; jp: (wordJp: string) => string }>
  > = {
    "职场工作": [
      { zh: (w) => `我啱啱同阿姐${w}咗喇。`, jp: (j) => `ngo5 ngaam1 ngaam1 tung4 aa3 ze2 ${j} zo2 laa3.` },
      { zh: (w) => `呢单嘢下晝要${w}呀。`, jp: (j) => `ni1 daan1 je5 haa6 zau3 jiu3 ${j} aa3.` },
      { zh: (w) => `大佬催紧我快啲${w}。`, jp: (j) => `daai6 lou2 ceoi1 gan2 ngo5 faai3 di1 ${j}.` },
    ],
    "饮食文化": [
      { zh: (w) => `我哋今晚去茶記${w}呀。`, jp: (j) => `ngo5 dei6 gam1 maan5 heoi3 caa4 gei3 ${j} aa3.` },
      { zh: (w) => `呢味我次次都會${w}。`, jp: (j) => `ni1 mei6 ngo5 ci3 ci3 dou1 wui5 ${j}.` },
      { zh: (w) => `阿媽話今日要${w}喇。`, jp: (j) => `aa3 maa1 waa6 gam1 jat6 jiu3 ${j} laa3.` },
    ],
    "交通与社交": [
      { zh: (w) => `你陣間同我一齊${w}啦。`, jp: (j) => `nei5 zan6 gaan1 tung4 ngo5 jat1 cai4 ${j} laa1.` },
      { zh: (w) => `放工之後我想${w}吓。`, jp: (j) => `fong3 gung1 zi1 hau6 ngo5 soeng2 ${j} haa5.` },
      { zh: (w) => `而家塞緊車，唯有${w}。`, jp: (j) => `ji4 gaa1 sak1 gan2 ce1, wai4 jau5 ${j}.` },
    ],
    "生活情绪": [
      { zh: (w) => `佢今日成個人都${w}咗。`, jp: (j) => `keoi5 gam1 jat6 seng4 go3 jan4 dou1 ${j} zo2.` },
      { zh: (w) => `聽到呢句我即刻${w}。`, jp: (j) => `teng1 dou2 ni1 geoi3 ngo5 zik1 hak1 ${j}.` },
      { zh: (w) => `你唔使驚，我冇${w}。`, jp: (j) => `nei5 m4 sai2 geng1, ngo5 mou5 ${j}.` },
    ],
    "地道口语": [
      { zh: (w) => `佢啱啱又喺度${w}喇。`, jp: (j) => `keoi5 ngaam1 ngaam1 jau6 hai2 dou6 ${j} laa3.` },
      { zh: (w) => `呢件事真係好${w}囉。`, jp: (j) => `ni1 gin6 si6 zan1 hai6 hou2 ${j} lo1.` },
      { zh: (w) => `你講乜都好，唔好${w}。`, jp: (j) => `nei5 gong2 mat1 dou1 hou2, m4 hou2 ${j}.` },
    ],
  };

  const templates = templatesByCategory[category];
  return raw.map(([canto, mandarin, jyutping], index) => {
    const template = templates[index % templates.length];
    const sentence = template.zh(canto);
    const sentence_jyutping = template.jp(jyutping);

    return {
      id: `${prefix}-${String(index + 1).padStart(3, "0")}`,
      category,
      canto,
      mandarin,
      jyutping,
      sentence,
      sentence_jyutping,
      sentence_mandarin: `日常会讲：${mandarin}。`,
      // Backward compatibility for current UI/data consumers.
      sentence_pinyin: sentence_jyutping,
    };
  });
}

function makeSentenceEntries(raw: RawSentenceEntry[], category: PracticeCategory, prefix: string): PracticeVocab[] {
  return raw.map(([canto, mandarin, jyutping, sentence, sentence_pinyin], index) => ({
    id: `${prefix}-${String(index + 1).padStart(3, "0")}`,
    category,
    canto,
    mandarin,
    jyutping,
    sentence,
    sentence_jyutping: sentence_pinyin,
    sentence_mandarin: `日常会讲：${mandarin}。`,
    sentence_pinyin,
  }));
}

const FIRST_BATCH_OVERRIDES: Record<
  string,
  { sentence: string; sentence_jyutping: string; sentence_mandarin: string }
> = {
  "work-001": { sentence: "晨早九点準時開會喇。", sentence_jyutping: "san4 zou2 gau2 dim2 zeon2 si4 hoi1 wui6 laa3.", sentence_mandarin: "一早九点准时开会了。" },
  "work-002": { sentence: "散會未呀？仲要改稿喎。", sentence_jyutping: "saan3 wui6 mei6 aa3? zung6 jiu3 goi2 gou2 wo3.", sentence_mandarin: "散会了吗？还得改稿呢。" },
  "work-003": { sentence: "呢個會議拖到晏晝喇。", sentence_jyutping: "ni1 go3 wui6 ji5 to1 dou3 aan3 zau3 laa3.", sentence_mandarin: "这场会议拖到下午了。" },
  "work-004": { sentence: "議程改咗，問答擺最後。", sentence_jyutping: "ji5 cing4 goi2 zo2, man6 daap3 baai2 zeoi3 hau6.", sentence_mandarin: "议程改了，问答放在最后。" },
  "work-005": { sentence: "今日輪到阿May主持。", sentence_jyutping: "gam1 jat6 leon4 dou3 aa3 mei1 zyu2 ci4.", sentence_mandarin: "今天轮到May来主持。" },
  "work-006": { sentence: "重點記錄低，唔好漏呀。", sentence_jyutping: "zung6 dim2 gei3 luk6 dai1, m4 hou2 lau6 aa3.", sentence_mandarin: "重点记下来，别漏了。" },
  "work-007": { sentence: "嗰單客訴你跟進咗未？", sentence_jyutping: "go2 daan1 haak3 sou3 nei5 gan1 zeon3 zo2 mei6?", sentence_mandarin: "那单客诉你跟进了吗？" },
  "work-008": { sentence: "食完飯上去同大佬匯報。", sentence_jyutping: "sik6 jyun4 faan6 soeng5 heoi3 tung4 daai6 lou2 wui6 bou3.", sentence_mandarin: "吃完饭上去向主管汇报。" },
  "work-009": { sentence: "份報告今晚一定要交。", sentence_jyutping: "fan6 bou3 gou3 gam1 maan5 jat1 ding6 jiu3 gaau1.", sentence_mandarin: "这份报告今晚一定要交。" },
  "work-010": { sentence: "臨收工先寫報告，攰爆。", sentence_jyutping: "lam4 sau1 gung1 sin1 se2 bou3 gou3, gui6 baau3.", sentence_mandarin: "快下班才写报告，累爆了。" },
  "work-011": { sentence: "三分鐘簡報，講重點得。", sentence_jyutping: "saam1 fan1 zung1 gaan2 bou3, gong2 zung6 dim2 dak1.", sentence_mandarin: "三分钟简报，讲重点就行。" },
  "work-012": { sentence: "計劃變咗，聽日再傾。", sentence_jyutping: "gai3 waak6 bin3 zo2, ting1 jat6 zoi3 king1.", sentence_mandarin: "计划变了，明天再谈。" },
  "work-013": { sentence: "A方案唔得，轉B啦。", sentence_jyutping: "ei1 fong1 on3 m4 dak1, zyun2 bi1 laa1.", sentence_mandarin: "A方案不行，换B吧。" },
  "work-014": { sentence: "預算得咁多，點搞先？", sentence_jyutping: "jyu5 syun3 dak1 gam3 do1, dim2 gaau2 sin1?", sentence_mandarin: "预算就这么多，怎么办？" },
  "work-015": { sentence: "等審批批咗先可以買。", sentence_jyutping: "dang2 sam1 pai3 pai1 zo2 sin1 ho2 ji5 maai5.", sentence_mandarin: "等审批通过后才能买。" },
  "work-016": { sentence: "批核慢成咁，急死人喇。", sentence_jyutping: "pai1 hat6 maan6 seng4 gam3, gap1 sei2 jan4 laa3.", sentence_mandarin: "批核这么慢，急死人了。" },
  "work-017": { sentence: "呢度簽名，右下角呀。", sentence_jyutping: "ni1 dou6 cim1 meng2, jau6 haa6 gok3 aa3.", sentence_mandarin: "这里签名，在右下角。" },
  "work-018": { sentence: "老闆叫你即刻簽文件。", sentence_jyutping: "lou5 baan2 giu3 nei5 zik1 hak1 cim1 man4 gin2.", sentence_mandarin: "老板让你马上签文件。" },
  "work-019": { sentence: "文件擺咗喺共用盤。", sentence_jyutping: "man4 gin2 baai2 zo2 hai2 gung6 jung6 pun4.", sentence_mandarin: "文件放在共享盘里了。" },
  "work-020": { sentence: "舊檔案唔見咗，邊個拎走？", sentence_jyutping: "gau6 dong3 on2 m4 gin3 zo2, bin1 go3 ling1 zau2?", sentence_mandarin: "旧档案不见了，谁拿走的？" },
  "work-021": { sentence: "合約條文要睇真啲。", sentence_jyutping: "hap6 joek3 tiu4 man4 jiu3 tai2 zan1 di1.", sentence_mandarin: "合同条文要看仔细点。" },
  "work-022": { sentence: "呢條款太辣，客唔簽。", sentence_jyutping: "ni1 tiu4 fun2 taai3 laat6, haak3 m4 cim1.", sentence_mandarin: "这条款太苛刻，客户不签。" },
  "work-023": { sentence: "報價咁高，客皺晒眉。", sentence_jyutping: "bou3 gaa3 gam3 gou1, haak3 zau3 saai3 mei4.", sentence_mandarin: "报价这么高，客户都皱眉了。" },
  "work-024": { sentence: "再議價啦，仲有位減。", sentence_jyutping: "zoi3 ji5 gaa3 laa1, zung6 jau5 wai2 gaam2.", sentence_mandarin: "再议一下价吧，还有空间降。" },
  "work-025": { sentence: "下個月投標，準備好未？", sentence_jyutping: "haa6 go3 jyut6 tau4 biu1, zeon2 bei6 hou2 mei6?", sentence_mandarin: "下个月投标，准备好了没？" },
  "work-026": { sentence: "恭喜你哋中標喇！", sentence_jyutping: "gung1 hei2 nei5 dei6 zung3 biu1 laa3!", sentence_mandarin: "恭喜你们中标了！" },
  "work-027": { sentence: "成本升咗，利潤會薄。", sentence_jyutping: "sing4 bun2 sing1 zo2, lei6 jeon6 wui5 bok6.", sentence_mandarin: "成本涨了，利润会变薄。" },
  "work-028": { sentence: "老細話利潤要再升。", sentence_jyutping: "lou5 sai3 waa6 lei6 jeon6 jiu3 zoi3 sing1.", sentence_mandarin: "老板说利润还要再提。" },
  "work-029": { sentence: "今季業績靚到爆燈。", sentence_jyutping: "gam1 gwai3 jip6 zik1 leng3 dou3 baau3 dang1.", sentence_mandarin: "这季业绩亮眼到爆。" },
  "work-030": { sentence: "呢個指標未達標喎。", sentence_jyutping: "ni1 go3 zi2 biu1 mei6 daat6 biu1 wo3.", sentence_mandarin: "这个指标还没达标呢。" },
  "work-031": { sentence: "目標定低咗就衝啦。", sentence_jyutping: "muk6 biu1 ding6 dai1 zo2 zau6 cung1 laa1.", sentence_mandarin: "目标定下了就冲吧。" },
  "work-032": { sentence: "今日表現算係超班。", sentence_jyutping: "gam1 jat6 biu2 jin6 syun3 hai6 ciu1 baan1.", sentence_mandarin: "今天表现算是超常发挥。" },
  "work-033": { sentence: "咁樣做先至有效率。", sentence_jyutping: "gam3 joeng6 zou6 sin1 zi3 jau5 haau6 leot6.", sentence_mandarin: "这样做才有效率。" },
  "work-034": { sentence: "流程太長，客等到躁。", sentence_jyutping: "lau4 cing4 taai3 coeng4, haak3 dang2 dou3 cou3.", sentence_mandarin: "流程太长，客户等得烦躁。" },
  "work-035": { sentence: "系統死機，成組停晒。", sentence_jyutping: "hai6 tung2 sei2 gei1, seng4 zou2 ting4 saai3.", sentence_mandarin: "系统宕机，整组都停住了。" },
  "work-036": { sentence: "我冇權限開呢個檔。", sentence_jyutping: "ngo5 mou5 kyun4 han6 hoi1 ni1 go3 dong2.", sentence_mandarin: "我没有权限打开这个文件。" },
  "work-037": { sentence: "新同事賬號開咗未？", sentence_jyutping: "san1 tung4 si6 zoeng3 hou6 hoi1 zo2 mei6?", sentence_mandarin: "新同事的账号开了吗？" },
  "work-038": { sentence: "密碼又過期，真麻煩。", sentence_jyutping: "mat6 maa5 jau6 gwo3 kei4, zan1 maa4 faan4.", sentence_mandarin: "密码又过期了，真麻烦。" },
  "work-039": { sentence: "登入唔到？搵IT幫手啦。", sentence_jyutping: "dang1 jap6 m4 dou2? wan2 ai1 ti1 bong1 sau2 laa1.", sentence_mandarin: "登不上去？找IT帮忙吧。" },
  "work-040": { sentence: "走之前記得登出呀。", sentence_jyutping: "zau2 zi1 cin4 gei3 dak1 dang1 ceot1 aa3.", sentence_mandarin: "走之前记得登出哦。" },
  "work-041": { sentence: "相片上傳咗去雲端未？", sentence_jyutping: "soeng2 pin3 soeng6 cyun4 zo2 heoi3 wan4 dyun1 mei6?", sentence_mandarin: "照片上传到云端了吗？" },
  "work-042": { sentence: "先下載附件再開會。", sentence_jyutping: "sin1 haa6 zoi6 fu6 gin2 zoi3 hoi1 wui6.", sentence_mandarin: "先下载附件再开会。" },
  "work-043": { sentence: "版本更新咗，快啲試。", sentence_jyutping: "baan2 bun2 gang1 san1 zo2, faai3 di1 si3.", sentence_mandarin: "版本更新了，快去试试。" },
  "work-044": { sentence: "改完記得撳保存喇。", sentence_jyutping: "goi2 jyun4 gei3 dak1 gam6 bou2 cyun4 laa3.", sentence_mandarin: "改完记得点保存。" },
  "work-045": { sentence: "呢份重複檔可以刪除。", sentence_jyutping: "ni1 fan6 cung4 fuk1 dong2 ho2 ji5 saat3 ceoi4.", sentence_mandarin: "这份重复文件可以删掉。" },
  "work-046": { sentence: "先複製模板再改內容。", sentence_jyutping: "sin1 fuk1 zai3 mou4 baan2 zoi3 goi2 noi6 jung4.", sentence_mandarin: "先复制模板再改内容。" },
  "work-047": { sentence: "喺呢格貼上就得喇。", sentence_jyutping: "hai2 ni1 gaak3 tip3 soeng5 zau6 dak1 laa3.", sentence_mandarin: "贴到这个栏位就可以了。" },
  "work-048": { sentence: "客喺樓下等，快啲打印。", sentence_jyutping: "haak3 hai2 lau4 haa6 dang2, faai3 di1 daai2 jan3.", sentence_mandarin: "客户在楼下等，快点打印。" },
  "work-049": { sentence: "身分證掃描完傳俾我。", sentence_jyutping: "san1 fan6 zing3 sou3 miu4 jyun4 cyun4 bei2 ngo5.", sentence_mandarin: "身份证扫完传给我。" },
  "work-050": { sentence: "今朝郵件爆晒個箱。", sentence_jyutping: "gam1 ziu1 jau6 gin2 baau3 saai3 go3 soeng1.", sentence_mandarin: "今天早上邮箱直接爆了。" },
  "work-051": { sentence: "快啲發郵件通知全組。", sentence_jyutping: "faai3 di1 faat3 jau4 gin2 tung1 zi1 cyun4 zou2.", sentence_mandarin: "快点发邮件通知全组。" },
  "work-052": { sentence: "呢封電郵語氣要客氣啲。", sentence_jyutping: "ni1 fung1 din6 jau4 jyu5 hei3 jiu3 haak3 hei3 di1.", sentence_mandarin: "这封电邮语气要客气点。" },
  "work-053": { sentence: "收件箱又塞爆咗喇。", sentence_jyutping: "sau1 gin6 soeng1 jau6 sak1 baau3 zo2 laa3.", sentence_mandarin: "收件箱又被塞爆了。" },
  "work-054": { sentence: "記得抄送阿May同阿Ken。", sentence_jyutping: "gei3 dak1 caau1 sung3 aa3 mei1 tung4 aa3 ken1.", sentence_mandarin: "记得抄送May和Ken。" },
  "work-055": { sentence: "附件太大，傳唔出去。", sentence_jyutping: "fu6 gin2 taai3 daai6, cyun4 m4 ceot1 heoi3.", sentence_mandarin: "附件太大，发不出去。" },
  "work-056": { sentence: "主題寫清楚先有人睇。", sentence_jyutping: "zyu2 tai4 se2 cing1 co2 sin1 jau5 jan4 tai2.", sentence_mandarin: "主题写清楚才有人看。" },
  "work-057": { sentence: "客覆咗未？等緊你回覆。", sentence_jyutping: "haak3 fuk1 zo2 mei6? dang2 gan2 nei5 wui4 fuk1.", sentence_mandarin: "客户回复了吗？大家在等你回复。" },
  "work-058": { sentence: "呢封幫我轉發俾老細。", sentence_jyutping: "ni1 fung1 bong1 ngo5 zyun2 faat3 bei2 lou5 sai3.", sentence_mandarin: "这封帮我转发给老板。" },
  "work-059": { sentence: "截止今晚六點，唔好拖。", sentence_jyutping: "zit3 zi2 gam1 maan5 luk6 dim2, m4 hou2 to1.", sentence_mandarin: "今晚六点截止，别再拖了。" },
  "work-060": { sentence: "限期改咗，聽日先交。", sentence_jyutping: "haan6 kei4 goi2 zo2, ting1 jat6 sin1 gaau1.", sentence_mandarin: "期限改了，明天再交。" },
  "work-061": { sentence: "排期排到下個禮拜喇。", sentence_jyutping: "paai4 kei4 paai4 dou3 haa6 go3 lai5 baai3 laa3.", sentence_mandarin: "排期已经排到下周了。" },
  "work-062": { sentence: "今日日程密到冇位抖。", sentence_jyutping: "gam1 jat6 jat6 cing4 mat6 dou3 mou5 wai2 tau2.", sentence_mandarin: "今天日程满到没空喘气。" },
  "work-063": { sentence: "你個日曆點解全灰色？", sentence_jyutping: "nei5 go3 jat6 lik6 dim2 gaai2 cyun4 fui1 sik1?", sentence_mandarin: "你这日历怎么全灰了？" },
  "work-064": { sentence: "電話提醒响咗三次喇。", sentence_jyutping: "din6 waa2 tai4 sing2 hoeng2 zo2 saam1 ci3 laa3.", sentence_mandarin: "手机提醒已经响三次了。" },
  "work-065": { sentence: "客人改咗時間再預約。", sentence_jyutping: "haak3 jan4 goi2 zo2 si4 gaan3 zoi3 jyu6 joek3.", sentence_mandarin: "客人改了时间，要重新预约。" },
  "work-066": { sentence: "呢位客戶要求好高㗎。", sentence_jyutping: "ni1 wai2 haak3 wu6 jiu1 kau4 hou2 gou1 gaa3.", sentence_mandarin: "这位客户要求很高。" },
  "work-067": { sentence: "客人喺大堂等緊你喎。", sentence_jyutping: "haak3 jan4 hai2 daai6 tong4 dang2 gan2 nei5 wo3.", sentence_mandarin: "客人在大堂等你呢。" },
  "work-068": { sentence: "同事話今晚一齊食飯。", sentence_jyutping: "tung4 si6 waa6 gam1 maan5 jat1 cai4 sik6 faan6.", sentence_mandarin: "同事说今晚一起吃饭。" },
  "work-069": { sentence: "呢單你同拍檔夾住做。", sentence_jyutping: "ni1 daan1 nei5 tung4 paak3 dong3 gaap3 zyu6 zou6.", sentence_mandarin: "这单你和搭档一起做。" },
  "work-070": { sentence: "團隊默契好，做嘢快。", sentence_jyutping: "tyun4 deoi6 mak6 kai3 hou2, zou6 je5 faai3.", sentence_mandarin: "团队默契好，做事很快。" },
  "work-071": { sentence: "呢件唔關我部門事喎。", sentence_jyutping: "ni1 gin6 m4 gwaan1 ngo5 bou6 mun4 si6 wo3.", sentence_mandarin: "这件事不归我们部门管。" },
  "work-072": { sentence: "人事叫你補返份表。", sentence_jyutping: "jan4 si6 giu3 nei5 bou2 faan1 fan6 biu2.", sentence_mandarin: "人事让你补回那张表。" },
  "work-073": { sentence: "行政嗰邊仲未覆我。", sentence_jyutping: "hang4 zing3 go2 bin1 zung6 mei6 fuk1 ngo5.", sentence_mandarin: "行政那边还没回复我。" },
  "work-074": { sentence: "財務卡咗數，出唔到。", sentence_jyutping: "coi4 mou6 kaat1 zo2 sou3, ceot1 m4 dou2.", sentence_mandarin: "财务卡住了，款项出不来。" },
  "work-075": { sentence: "市場部話要再試水溫。", sentence_jyutping: "si5 coeng4 bou6 waa6 jiu3 zoi3 si3 seoi2 wan1.", sentence_mandarin: "市场部说要再试试水温。" },
  "work-076": { sentence: "銷售衝數衝到夜一夜。", sentence_jyutping: "siu1 sau2 cung1 sou3 cung1 dou3 je6 jat1 je6.", sentence_mandarin: "销售冲业绩冲到很晚。" },
  "work-077": { sentence: "採購價再壓低少少啦。", sentence_jyutping: "caai2 gau3 gaa3 zoi3 aat3 dai1 siu2 siu2 laa1.", sentence_mandarin: "采购价再压低一点吧。" },
  "work-078": { sentence: "倉庫啲貨擺到冇位喇。", sentence_jyutping: "cong1 fu3 di1 fo3 baai2 dou3 mou5 wai2 laa3.", sentence_mandarin: "仓库货堆到没位置了。" },
  "work-079": { sentence: "物流延誤，客即刻催。", sentence_jyutping: "mat6 lau4 jin4 ng6, haak3 zik1 hak1 ceoi1.", sentence_mandarin: "物流延误，客户马上催单。" },
  "work-080": { sentence: "供應跟唔上，點交貨呀？", sentence_jyutping: "gung1 jing3 gan1 m4 soeng5, dim2 gaau1 fo3 aa3?", sentence_mandarin: "供应跟不上，怎么交货？" },
  "work-081": { sentence: "供應商突然加價，痴線。", sentence_jyutping: "gung1 jing3 soeng1 dat6 jin4 gaa1 gaa3, ci1 sin3.", sentence_mandarin: "供应商突然涨价，太离谱了。" },
  "work-082": { sentence: "老闆話呢單一定要贏。", sentence_jyutping: "lou5 baan2 waa6 ni1 daan1 jat1 ding6 jiu3 jeng4.", sentence_mandarin: "老板说这单一定要拿下。" },
  "work-083": { sentence: "大佬今日心情幾好喎。", sentence_jyutping: "daai6 lou2 gam1 jat6 sam1 cing4 gei2 hou2 wo3.", sentence_mandarin: "主管今天心情还不错。" },
  "work-084": { sentence: "上司喺會議室等緊人。", sentence_jyutping: "soeng6 si1 hai2 wui6 ji5 sat1 dang2 gan2 jan4.", sentence_mandarin: "上司在会议室等人。" },
  "work-085": { sentence: "經理叫我哋重做一次。", sentence_jyutping: "ging2 lei5 giu3 ngo5 dei6 cung4 zou6 jat1 ci3.", sentence_mandarin: "经理让我们重做一遍。" },
  "work-086": { sentence: "總監落咗場，氣氛唔同。", sentence_jyutping: "zung2 gaam1 lok6 zo2 coeng4, hei3 fan1 m4 tung4.", sentence_mandarin: "总监一到场，气氛就不一样了。" },
  "work-087": { sentence: "秘書已經幫你book房。", sentence_jyutping: "bei3 syu1 ji5 ging1 bong1 nei5 buk1 fong2.", sentence_mandarin: "秘书已经帮你订好会议室了。" },
  "work-088": { sentence: "前台話有快遞俾你。", sentence_jyutping: "cin4 toi4 waa6 jau5 faai3 dai6 bei2 nei5.", sentence_mandarin: "前台说有你的快递。" },
  "work-089": { sentence: "寫字樓冷氣凍到震。", sentence_jyutping: "se2 zi6 lau4 laang5 hei3 dung3 dou3 zan3.", sentence_mandarin: "办公室冷气冷到发抖。" },
  "work-090": { sentence: "工位太亂，收拾下先。", sentence_jyutping: "gung1 wai6 taai3 lyun6, sau1 sap6 haa5 sin1.", sentence_mandarin: "工位太乱了，先收拾一下。" },
  "work-091": { sentence: "會議室滿咗，轉細房。", sentence_jyutping: "wui6 ji5 sat1 mun5 zo2, zyun2 sai3 fong2.", sentence_mandarin: "会议室满了，换小房间。" },
  "work-092": { sentence: "茶水間得返半壺咖啡。", sentence_jyutping: "caa4 seoi2 gaan1 dak1 faan1 bun3 wu4 gaa3 fe1.", sentence_mandarin: "茶水间只剩半壶咖啡了。" },
  "work-093": { sentence: "今朝打卡遲咗兩分鐘。", sentence_jyutping: "gam1 ziu1 daa2 kaat1 ci4 zo2 loeng5 fan1 zung1.", sentence_mandarin: "今天打卡迟了两分钟。" },
  "work-094": { sentence: "又加班？真係頂唔順。", sentence_jyutping: "jau6 gaa1 baan1? zan1 hai6 ding2 m4 seon6.", sentence_mandarin: "又加班？真的快扛不住了。" },
  "work-095": { sentence: "放工喇，行去食碗麵。", sentence_jyutping: "fong3 gung1 laa3, haang4 heoi3 sik6 wun2 min6.", sentence_mandarin: "下班啦，走去吃碗面。" },
  "work-096": { sentence: "屋企有事，想請假一日。", sentence_jyutping: "uk1 kei2 jau5 si6, soeng2 ceng2 gaa3 jat1 jat6.", sentence_mandarin: "家里有事，想请一天假。" },
  "work-097": { sentence: "補假留到下個月先放。", sentence_jyutping: "bou2 gaa3 lau4 dou3 haa6 go3 jyut6 sin1 fong3.", sentence_mandarin: "补假留到下个月再放。" },
  "work-098": { sentence: "發燒發到暈，請病假。", sentence_jyutping: "faat3 siu1 faat3 dou3 wan4, ceng2 beng6 gaa3.", sentence_mandarin: "发烧发到头晕，得请病假。" },
  "work-099": { sentence: "地鐵故障，遲到唔怪我。", sentence_jyutping: "dei6 tit3 gu3 zoeng6, ci4 dou3 m4 gwaai3 ngo5.", sentence_mandarin: "地铁故障，迟到真不怪我。" },
  "work-100": { sentence: "早退半粒鐘，要報備。", sentence_jyutping: "zou2 teoi3 bun3 nap1 zung1, jiu3 bou3 bei6.", sentence_mandarin: "提前半小时走，要先报备。" },
  "work-101": { sentence: "下星期飛深圳出差三日。", sentence_jyutping: "haa6 sing1 kei4 fei1 sam1 zan3 ceot1 caai1 saam1 jat6.", sentence_mandarin: "下周飞深圳出差三天。" },
  "work-102": { sentence: "晏晝去中環見客，唔好遲。", sentence_jyutping: "aan3 zau3 heoi3 zung1 waan4 gin3 haak3, m4 hou2 ci4.", sentence_mandarin: "下午去中环见客户，别迟到。" },
  "work-103": { sentence: "培訓手冊睇咗先入堂。", sentence_jyutping: "pui4 fan3 sau2 caak3 tai2 zo2 sin1 jap6 tong4.", sentence_mandarin: "先看培训手册再进课室。" },
  "work-104": { sentence: "實習生今日第一次跟場。", sentence_jyutping: "sat6 zaap6 saang1 gam1 jat6 dai6 jat1 ci3 gan1 coeng4.", sentence_mandarin: "实习生今天第一次跟场。" },
  "work-105": { sentence: "試用期仲有兩個禮拜。", sentence_jyutping: "si3 jung6 kei4 zung6 jau5 loeng5 go3 lai5 baai3.", sentence_mandarin: "试用期还剩两周。" },
  "work-106": { sentence: "轉正通知終於出咗喇！", sentence_jyutping: "zyun2 zing3 tung1 zi1 zung1 jyu1 ceot1 zo2 laa3!", sentence_mandarin: "转正通知终于发出来了！" },
  "work-107": { sentence: "升職咗請食飯，走得甩？", sentence_jyutping: "sing1 zik1 zo2 ceng2 sik6 faan6, zau2 dak1 lat1?", sentence_mandarin: "升职了还不请吃饭，跑得掉吗？" },
  "work-108": { sentence: "加薪幅度咁少，點夠呀。", sentence_jyutping: "gaa1 san1 fuk1 dou6 gam3 siu2, dim2 gau3 aa3.", sentence_mandarin: "加薪幅度这么小，哪够啊。" },
  "work-109": { sentence: "今個月人工遲咗兩日。", sentence_jyutping: "gam1 go3 jyut6 jan4 gung1 ci4 zo2 loeng5 jat6.", sentence_mandarin: "这个月工资晚了两天。" },
  "work-110": { sentence: "年尾獎金有冇機會加？", sentence_jyutping: "nin4 mei5 zoeng2 gam1 jau5 mou5 gei1 wui6 gaa1?", sentence_mandarin: "年终奖金还有机会加吗？" },
  "work-111": { sentence: "呢份工福利算幾齊全。", sentence_jyutping: "ni1 fan6 gung1 fuk1 lei6 syun3 gei2 cai4 cyun4.", sentence_mandarin: "这份工作的福利算挺齐全。" },
  "work-112": { sentence: "強積金戶口記得轉番。", sentence_jyutping: "koeng4 zik1 gam1 wu6 hau2 gei3 dak1 zyun2 faan1.", sentence_mandarin: "强积金账户记得转回来。" },
  "work-113": { sentence: "離職前要清晒手尾先。", sentence_jyutping: "lei4 zik1 cin4 jiu3 cing1 saai3 sau2 mei5 sin1.", sentence_mandarin: "离职前要把尾巴都收干净。" },
  "work-114": { sentence: "辭職信寫好未？交咗未？", sentence_jyutping: "ci4 zik1 seon3 se2 hou2 mei6? gaau1 zo2 mei6?", sentence_mandarin: "辞职信写好没？递了没？" },
  "work-115": { sentence: "交接清單逐項對一次。", sentence_jyutping: "gaau1 zip3 cing1 daan1 zuk6 hong6 deoi3 jat1 ci3.", sentence_mandarin: "交接清单逐项再核一次。" },
  "work-116": { sentence: "遠程辦公都要準時上線。", sentence_jyutping: "jyun5 cing4 baan1 gung1 dou1 jiu3 zeon2 si4 soeng5 sin3.", sentence_mandarin: "远程办公也要准时上线。" },
  "work-117": { sentence: "喺屋企辦公，網絡要穩。", sentence_jyutping: "hai2 uk1 kei2 baan1 gung1, mong5 lok6 jiu3 wan2.", sentence_mandarin: "在家办公，网络一定要稳。" },
  "work-118": { sentence: "今晚又開OT，真係攰。", sentence_jyutping: "gam1 maan5 jau6 hoi1 ou1 ti1, zan1 hai6 gui6.", sentence_mandarin: "今晚又加班，真的累。" },
  "work-119": { sentence: "趕deadline趕到眼都紅。", sentence_jyutping: "gon2 ded1 lai1 gon2 dou3 ngaan5 dou1 hung4.", sentence_mandarin: "赶deadline赶到眼都红了。" },
  "work-120": { sentence: "寫proposal寫到凌晨兩點。", sentence_jyutping: "se2 propou1 sou3 se2 dou3 ling4 sang4 loeng5 dim2.", sentence_mandarin: "写proposal写到凌晨两点。" },
  "food-001": { sentence: "星期日同屋企人去飲茶。", sentence_jyutping: "sing1 kei4 jat6 tung4 uk1 kei2 jan4 heoi3 jam2 caa4.", sentence_mandarin: "周日和家人去饮茶。" },
  "food-002": { sentence: "未食飯住，等阿媽返嚟。", sentence_jyutping: "mei6 sik6 faan6 zyu6, dang2 aa3 maa1 faan1 lai4.", sentence_mandarin: "先别开饭，等妈妈回来。" },
  "food-003": { sentence: "食晏未呀？一齊落樓啦。", sentence_jyutping: "sik6 aan3 mei6 aa3? jat1 cai4 lok6 lau4 laa1.", sentence_mandarin: "吃午饭了吗？一起下楼吧。" },
  "food-004": { sentence: "半夜肚餓，去食宵夜！", sentence_jyutping: "bun3 je6 tou5 ngo6, heoi3 sik6 siu1 je6!", sentence_mandarin: "半夜肚子饿，去吃宵夜！" },
  "food-005": { sentence: "呢間點心新鮮，值得等。", sentence_jyutping: "ni1 gaan1 dim2 sam1 san1 sin1, zik6 dak1 dang2.", sentence_mandarin: "这家点心新鲜，值得等。" },
  "food-006": { sentence: "蝦餃賣晒？咁快手嘅！", sentence_jyutping: "haa1 gaau2 maai6 saai3? gam3 faai3 sau2 ge3!", sentence_mandarin: "虾饺卖完了？这么快！" },
  "food-007": { sentence: "燒賣趁熱食先夠彈牙。", sentence_jyutping: "siu1 maai6 can3 jit6 sik6 sin1 gau3 daan6 ngaa4.", sentence_mandarin: "烧卖趁热吃才够弹牙。" },
  "food-008": { sentence: "腸粉加豉油，唔該。", sentence_jyutping: "coeng4 fan2 gaa1 si6 jau4, m4 goi1.", sentence_mandarin: "肠粉加点酱油，谢谢。" },
  "food-009": { sentence: "叉燒包一開蓋就香。", sentence_jyutping: "caa1 siu1 baau1 jat1 hoi1 koi3 zau6 hoeng1.", sentence_mandarin: "叉烧包一揭盖就很香。" },
  "food-010": { sentence: "奶茶走甜，唔該曬。", sentence_jyutping: "naai5 caa4 zau2 tim4, m4 goi1 saai3.", sentence_mandarin: "奶茶少甜，谢啦。" },
  "food-011": { sentence: "今日太熱，叫凍檸茶啦。", sentence_jyutping: "gam1 jat6 taai3 jit6, giu3 dung3 ning4 caa4 laa1.", sentence_mandarin: "今天太热了，点杯冰柠茶吧。" },
  "food-012": { sentence: "一杯鴛鴦，提神最快。", sentence_jyutping: "jat1 bui1 jyun1 joeng1, tai4 san4 zeoi3 faai3.", sentence_mandarin: "来杯鸳鸯，提神最快。" },
  "food-013": { sentence: "咖啡要齋啡，唔落糖。", sentence_jyutping: "gaa3 fe1 jiu3 zaai1 fe1, m4 lok6 tong4.", sentence_mandarin: "咖啡要黑咖，不加糖。" },
  "food-014": { sentence: "菠蘿包熱辣辣先正。", sentence_jyutping: "bo1 lo4 baau1 jit6 laat6 laat6 sin1 zeng3.", sentence_mandarin: "菠萝包热腾腾才过瘾。" },
  "food-015": { sentence: "蛋撻出爐喇，快啲買。", sentence_jyutping: "daan6 taat1 ceot1 lou4 laa3, faai3 di1 maai5.", sentence_mandarin: "蛋挞出炉了，赶紧买。" },
  "food-016": { sentence: "西多士加煉奶，邪惡啲。", sentence_jyutping: "sai1 do1 si2 gaa1 lin6 naai5, je4 ok3 di1.", sentence_mandarin: "西多士加炼奶，放纵一点。" },
  "food-017": { sentence: "茶餐廳等位要有耐性。", sentence_jyutping: "caa4 caan1 teng1 dang2 wai2 jiu3 jau5 noi6 sing3.", sentence_mandarin: "茶餐厅等位得有耐心。" },
  "food-018": { sentence: "卡位坐得舒服，慢慢食。", sentence_jyutping: "kaa1 wai2 co5 dak1 syu1 fuk6, maan6 maan6 sik6.", sentence_mandarin: "卡座坐得舒服，慢慢吃。" },
  "food-019": { sentence: "諗好未？落單喇喎。", sentence_jyutping: "nam2 hou2 mei6? lok6 daan1 laa3 wo3.", sentence_mandarin: "想好了吗？要下单了哦。" },
  "food-020": { sentence: "等位耐啲都值，唔怕。", sentence_jyutping: "dang2 wai2 noi6 di1 dou1 zik6, m4 paa3.", sentence_mandarin: "等位久一点也值，不怕。" },
  "food-021": { sentence: "食飽就埋單，唔好坐住。", sentence_jyutping: "sik6 baau2 zau6 maai4 daan1, m4 hou2 co5 zyu6.", sentence_mandarin: "吃饱就结账，别一直占座。" },
  "food-022": { sentence: "AA制最公平，冇爭拗。", sentence_jyutping: "ei1 ei1 zai3 zeoi3 gung1 ping4, mou5 zang1 ngaau3.", sentence_mandarin: "AA制最公平，不会扯皮。" },
  "food-023": { sentence: "食唔晒就打包返屋企。", sentence_jyutping: "sik6 m4 saai3 zau6 daa2 baau1 faan1 uk1 kei2.", sentence_mandarin: "吃不完就打包回家。" },
  "food-024": { sentence: "今晚太攰，叫外賣算。", sentence_jyutping: "gam1 maan5 taai3 gui6, giu3 ngoi6 maai6 syun3.", sentence_mandarin: "今晚太累了，叫外卖算了。" },
  "food-025": { sentence: "堂食定外賣？你揀啦。", sentence_jyutping: "tong4 sik6 ding6 ngoi6 maai6? nei5 gaan2 laa1.", sentence_mandarin: "堂食还是外卖？你选吧。" },
  "food-026": { sentence: "走糖得唔得？醫生叫戒。", sentence_jyutping: "zau2 tong4 dak1 m4 dak1? ji1 sang1 giu3 gaai3.", sentence_mandarin: "能不能少糖？医生让我戒糖。" },
  "food-027": { sentence: "走冰呀，喉嚨有啲痛。", sentence_jyutping: "zau2 bing1 aa3, hau4 lung4 jau5 di1 tung3.", sentence_mandarin: "去冰吧，喉咙有点痛。" },
  "food-028": { sentence: "少甜就啱，唔會膩。", sentence_jyutping: "siu2 tim4 zau6 ngaam1, m4 wui5 nei6.", sentence_mandarin: "少甜刚好，不会腻。" },
  "food-029": { sentence: "少冰都夠凍，唔使咁多。", sentence_jyutping: "siu2 bing1 dou1 gau3 dung3, m4 sai2 gam3 do1.", sentence_mandarin: "少冰也够冰，不用放太多。" },
  "food-030": { sentence: "熱飲暖胃，落雨天啱晒。", sentence_jyutping: "jit6 jam2 nyun5 wai6, lok6 jyu5 tin1 ngaam1 saai3.", sentence_mandarin: "热饮暖胃，下雨天最合适。" },
  "food-031": { sentence: "凍飲加兩蚊，照叫啦。", sentence_jyutping: "dung3 jam2 gaa1 loeng5 man1, ziu3 giu3 laa1.", sentence_mandarin: "冷饮加两块，也照点吧。" },
  "food-032": { sentence: "加料加珍珠，口感好啲。", sentence_jyutping: "gaa1 liu2 gaa1 zan1 zyu1, hau2 gam2 hou2 di1.", sentence_mandarin: "加料加珍珠，口感更好。" },
  "food-033": { sentence: "加底牛腩，食得更飽。", sentence_jyutping: "gaa1 dai2 ngau4 naam5, sik6 dak1 gang3 baau2.", sentence_mandarin: "加底牛腩，吃得更饱。" },
  "food-034": { sentence: "加飯啦，今日餓到震。", sentence_jyutping: "gaa1 faan6 laa1, gam1 jat6 ngo6 dou3 zan3.", sentence_mandarin: "加饭吧，今天饿到发抖。" },
  "food-035": { sentence: "加錢轉套餐，抵食啲。", sentence_jyutping: "gaa1 cin2 zyun2 tou3 caan1, dai2 sik6 di1.", sentence_mandarin: "加点钱换套餐，更划算。" },
  "food-036": { sentence: "例湯好清甜，記得飲。", sentence_jyutping: "lai6 tong1 hou2 cing1 tim4, gei3 dak1 jam2.", sentence_mandarin: "例汤很清甜，记得喝。" },
  "food-037": { sentence: "靚湯一啖落肚即刻暖。", sentence_jyutping: "leng3 tong1 jat1 daam6 lok6 tou5 zik1 hak1 nyun5.", sentence_mandarin: "好汤一入口，肚子立刻暖了。" },
  "food-038": { sentence: "白飯要熱辣辣先好食。", sentence_jyutping: "baak6 faan6 jiu3 jit6 laat6 laat6 sin1 hou2 sik6.", sentence_mandarin: "白饭要热腾腾才好吃。" },
  "food-039": { sentence: "炒飯粒粒分明，唔錯喎。", sentence_jyutping: "caau2 faan6 nap1 nap1 fan1 ming4, m4 co3 wo3.", sentence_mandarin: "炒饭粒粒分明，不错哦。" },
  "food-040": { sentence: "炒麵鑊氣夠，食落香。", sentence_jyutping: "caau2 min6 wok6 hei3 gau3, sik6 lok6 hoeng1.", sentence_mandarin: "炒面镬气够，吃起来很香。" },
  "food-041": { sentence: "河粉滑啲，阿婆都食得。", sentence_jyutping: "ho4 fan2 waat6 di1, aa3 po4 dou1 sik6 dak1.", sentence_mandarin: "河粉滑一点，老人家也吃得下。" },
  "food-042": { sentence: "米線走辣，陣間見客㗎。", sentence_jyutping: "mai5 sin3 zau2 laat6, zan6 gaan1 gin3 haak3 gaa3.", sentence_mandarin: "米线不要辣，等下要见客户。" },
  "food-043": { sentence: "雲吞皮薄餡靚，正呀。", sentence_jyutping: "wan4 tan1 pei4 bok6 haam2 leng3, zeng3 aa3.", sentence_mandarin: "云吞皮薄馅靓，真赞。" },
  "food-044": { sentence: "牛腩炆到腍晒，入味。", sentence_jyutping: "ngau4 naam5 man1 dou3 nam5 saai3, jap6 mei6.", sentence_mandarin: "牛腩炖得很软，很入味。" },
  "food-045": { sentence: "叉燒肥瘦啱啱好，掂。", sentence_jyutping: "caa1 siu1 fei4 sau3 ngaam1 ngaam1 hou2, dim6.", sentence_mandarin: "叉烧肥瘦刚好，很可以。" },
  "food-046": { sentence: "燒鵝皮脆肉嫩，唔簡單。", sentence_jyutping: "siu1 ngo4 pei4 ceoi3 juk6 nyun6, m4 gaan2 daan1.", sentence_mandarin: "烧鹅皮脆肉嫩，不简单。" },
  "food-047": { sentence: "白切雞要點薑葱先香。", sentence_jyutping: "baak6 cit3 gai1 jiu3 dim2 goeng1 cung1 sin1 hoeng1.", sentence_mandarin: "白切鸡要蘸姜葱才香。" },
  "food-048": { sentence: "豬扒炸得脆，啱細路。", sentence_jyutping: "zyu1 paa4 zaa3 dak1 ceoi3, ngaam1 sai3 lou6.", sentence_mandarin: "猪排炸得酥脆，小朋友会喜欢。" },
  "food-049": { sentence: "魚蛋彈牙，落咖喱最夾。", sentence_jyutping: "jyu4 daan2 daan6 ngaa4, lok6 gaa3 lei1 zeoi3 gaap3.", sentence_mandarin: "鱼蛋弹牙，配咖喱最搭。" },
  "food-050": { sentence: "車仔麵配料任揀，好玩。", sentence_jyutping: "ce1 zai2 min6 pui3 liu2 jam6 gaan2, hou2 waan2.", sentence_mandarin: "车仔面配料随你选，很有趣。" },
  "food-051": { sentence: "粥底夠綿，病咗都食得。", sentence_jyutping: "zuk1 dai2 gau3 min4, beng6 zo2 dou1 sik6 dak1.", sentence_mandarin: "粥底够绵，生病也吃得下。" },
  "food-052": { sentence: "凍天打邊爐最啱氣氛。", sentence_jyutping: "dung3 tin1 daa2 bin1 lou4 zeoi3 ngaam1 hei3 fan1.", sentence_mandarin: "冷天吃火锅最有气氛。" },
  "food-053": { sentence: "食甜品啦，今日辛苦晒。", sentence_jyutping: "sik6 tim4 ban2 laa1, gam1 jat6 san1 fu2 saai3.", sentence_mandarin: "吃个甜品吧，今天辛苦了。" },
  "food-054": { sentence: "糖水唔好太甜，少少就夠。", sentence_jyutping: "tong4 seoi2 m4 hou2 taai3 tim4, siu2 siu2 zau6 gau3.", sentence_mandarin: "糖水别太甜，微甜就够了。" },
  "food-055": { sentence: "芝士拉絲咁長，誇張喎。", sentence_jyutping: "zi1 si2 laai1 si1 gam3 coeng4, kwaa1 zoeng1 wo3.", sentence_mandarin: "芝士拉丝这么长，太夸张了。" },
  "food-056": { sentence: "醬料自己溝，唔使客氣。", sentence_jyutping: "zoeng3 liu2 zi6 gei2 kau1, m4 sai2 haak3 hei3.", sentence_mandarin: "酱料自己调，不用客气。" },
  "food-057": { sentence: "胡椒落少啲，怕辣親喉。", sentence_jyutping: "wu4 ziu1 lok6 siu2 di1, paa3 laat6 can1 hau4.", sentence_mandarin: "胡椒少放点，怕呛喉咙。" },
  "food-058": { sentence: "辣椒另外上，大家自己加。", sentence_jyutping: "laat6 ziu1 ling6 ngoi6 soeng5, daai6 gaa1 zi6 gei2 gaa1.", sentence_mandarin: "辣椒另上，大家自己加。" },
  "food-059": { sentence: "筷子唔夠，唔該加多對。", sentence_jyutping: "faai3 zi2 m4 gau3, m4 goi1 gaa1 do1 deoi3.", sentence_mandarin: "筷子不够，麻烦再加一双。" },
  "food-060": { sentence: "凍檸樂加片檸檬更醒神。", sentence_jyutping: "dung3 ning4 lok6 gaa1 pin3 ning4 mung1 gang3 seng2 san4.", sentence_mandarin: "冰柠可乐再加片柠檬更提神。" },
  "social-001": { sentence: "落雨咁大，不如飛的返屋企。", sentence_jyutping: "lok6 jyu5 gam3 daai6, bat1 jyu4 fei1 dik1 faan1 uk1 kei2.", sentence_mandarin: "雨这么大，不如打车回家。" },
  "social-002": { sentence: "的士司機識路，快好多。", sentence_jyutping: "dik1 si2 si1 gei1 sik1 lou6, faai3 hou2 do1.", sentence_mandarin: "的士司机认路，快很多。" },
  "social-003": { sentence: "巴士到站喇，快啲上車。", sentence_jyutping: "baa1 si2 dou3 zaam6 laa3, faai3 di1 soeng5 ce1.", sentence_mandarin: "巴士到站了，快上车。" },
  "social-004": { sentence: "小巴開得快，坐穩陣啲。", sentence_jyutping: "siu2 baa1 hoi1 dak1 faai3, co5 wan2 zan6 di1.", sentence_mandarin: "小巴开得快，坐稳一点。" },
  "social-005": { sentence: "地鐵轉線要行好遠喎。", sentence_jyutping: "dei6 tit3 zyun2 sin3 jiu3 haang4 hou2 jyun5 wo3.", sentence_mandarin: "地铁换线要走很远呢。" },
  "social-006": { sentence: "港鐵又逼爆，真係辛苦。", sentence_jyutping: "gong2 tit3 jau6 bik1 baau3, zan1 hai6 san1 fu2.", sentence_mandarin: "港铁又挤爆了，真辛苦。" },
  "social-007": { sentence: "趕火車呀，唔好再蘑菇。", sentence_jyutping: "gon2 fo2 ce1 aa3, m4 hou2 zoi3 mo4 gu1.", sentence_mandarin: "要赶火车，别再磨蹭了。" },
  "social-008": { sentence: "高鐵位好闊，坐得舒服。", sentence_jyutping: "gou1 tit3 wai2 hou2 fut3, co5 dak1 syu1 fuk6.", sentence_mandarin: "高铁座位很宽，坐得舒服。" },
  "social-009": { sentence: "搭渡輪過海，景色幾靚。", sentence_jyutping: "daap3 dou6 leon4 gwo3 hoi2, ging2 sik1 gei2 leng3.", sentence_mandarin: "坐渡轮过海，景色很美。" },
  "social-010": { sentence: "電車慢慢行，最有feel。", sentence_jyutping: "din6 ce1 maan6 maan6 haang4, zeoi3 jau5 fiu1.", sentence_mandarin: "电车慢慢开，最有感觉。" },
  "social-011": { sentence: "踩單車去海旁，夠晒爽。", sentence_jyutping: "caai2 daan1 ce1 heoi3 hoi2 pong4, gau3 saai3 song2.", sentence_mandarin: "骑单车去海边，特别爽。" },
  "social-012": { sentence: "私家車泊邊度先唔抄牌？", sentence_jyutping: "si1 gaa1 ce1 paak3 bin1 dou6 sin1 m4 caau1 paai4?", sentence_mandarin: "私家车停哪儿才不会吃罚单？" },
  "social-013": { sentence: "塞車塞到想落車行路。", sentence_jyutping: "sak1 ce1 sak1 dou3 soeng2 lok6 ce1 haang4 lou6.", sentence_mandarin: "堵车堵到想下车走路。" },
  "social-014": { sentence: "過海隧道又收費加咗喎。", sentence_jyutping: "gwo3 hoi2 seoi6 dou6 jau6 sau1 fai3 gaa1 zo2 wo3.", sentence_mandarin: "过海隧道收费又涨了呢。" },
  "social-015": { sentence: "轉車嗰陣記得拍卡呀。", sentence_jyutping: "zyun2 ce1 go2 zan6 gei3 dak1 paak3 kaat1 aa3.", sentence_mandarin: "换乘时记得刷卡哦。" },
  "social-016": { sentence: "到站先落車，咪心急。", sentence_jyutping: "dou3 zaam6 sin1 lok6 ce1, mai6 sam1 gap1.", sentence_mandarin: "到站再下车，别着急。" },
  "social-017": { sentence: "上車排隊啦，唔好攝位。", sentence_jyutping: "soeng5 ce1 paai4 deoi2 laa1, m4 hou2 sip3 wai2.", sentence_mandarin: "上车排队，别插队。" },
  "social-018": { sentence: "上車記得拍卡，唔好漏。", sentence_jyutping: "soeng5 ce1 gei3 dak1 paak3 kaat1, m4 hou2 lau6.", sentence_mandarin: "上车记得刷卡，别漏了。" },
  "social-019": { sentence: "八達通餘額唔夠，快啲增值。", sentence_jyutping: "baat3 daat6 tung1 jyu4 ngaak6 m4 gau3, faai3 di1 zang1 zik6.", sentence_mandarin: "八达通余额不够，赶紧充值。" },
  "social-020": { sentence: "月票抵唔抵？你自己計吓。", sentence_jyutping: "jyut6 piu3 dai2 m4 dai2? nei5 zi6 gei2 gai3 haa5.", sentence_mandarin: "月票划不划算？你自己算算。" },
  "social-021": { sentence: "車費又加，打工仔慘喇。", sentence_jyutping: "ce1 fai3 jau6 gaa1, daa2 gung1 zai2 caam2 laa3.", sentence_mandarin: "车费又涨，打工人太惨了。" },
  "social-022": { sentence: "喺車站等咗成粒鐘。", sentence_jyutping: "hai2 ce1 zaam6 dang2 zo2 seng4 nap1 zung1.", sentence_mandarin: "在车站等了整整一小时。" },
  "social-023": { sentence: "站頭人好多，排長龍呀。", sentence_jyutping: "zaam6 tau4 jan4 hou2 do1, paai4 coeng4 lung4 aa3.", sentence_mandarin: "站头人很多，排起长队了。" },
  "social-024": { sentence: "紅綠燈未轉，唔好亂衝。", sentence_jyutping: "hung4 luk6 dang1 mei6 zyun2, m4 hou2 lyun6 cung1.", sentence_mandarin: "红绿灯还没转，别乱冲。" },
  "social-025": { sentence: "過斑馬線先安全啲。", sentence_jyutping: "gwo3 baan1 maa5 sin3 sin1 on1 cyun4 di1.", sentence_mandarin: "先走斑马线更安全。" },
  "social-026": { sentence: "行人路窄，借借唔該。", sentence_jyutping: "haang4 jan4 lou6 zaak3, ze3 ze3 m4 goi1.", sentence_mandarin: "人行道太窄，借过一下。" },
  "social-027": { sentence: "星期六去行街，買衫先。", sentence_jyutping: "sing1 kei4 luk6 heoi3 haang4 gaai1, maai5 saam1 sin1.", sentence_mandarin: "周六去逛街，先买衣服。" },
  "social-028": { sentence: "新戲口碑好，今晚睇戲？", sentence_jyutping: "san1 hei3 hau2 bei1 hou2, gam1 maan5 tai2 hei3?", sentence_mandarin: "新片口碑不错，今晚看吗？" },
  "social-029": { sentence: "睇波嗌到失聲，真過癮。", sentence_jyutping: "tai2 bo1 aai3 dou3 sat1 sing1, zan1 gwo3 jan2.", sentence_mandarin: "看球喊到失声，真过瘾。" },
  "social-030": { sentence: "唱K唱到三點先散。", sentence_jyutping: "coeng3 kei1 coeng3 dou3 saam1 dim2 sin1 saan3.", sentence_mandarin: "唱K唱到三点才散场。" },
  "social-031": { sentence: "打機輸咗唔好嬲啦。", sentence_jyutping: "daa2 gei1 syu1 zo2 m4 hou2 nau1 laa1.", sentence_mandarin: "打游戏输了别生气。" },
  "social-032": { sentence: "天氣咁熱，先買杯飲嘢。", sentence_jyutping: "tin1 hei3 gam3 jit6, sin1 maai5 bui1 jam2 je5.", sentence_mandarin: "天气这么热，先买杯喝的。" },
  "social-033": { sentence: "約人約到最後甩底喎。", sentence_jyutping: "joek3 jan4 joek3 dou3 zeoi3 hau6 lat1 dai2 wo3.", sentence_mandarin: "约人约到最后被放鸽子了。" },
  "social-034": { sentence: "搵人搵咗半日都未見。", sentence_jyutping: "wan2 jan4 wan2 zo2 bun3 jat6 dou1 mei6 gin3.", sentence_mandarin: "找人找了半天还没见到。" },
  "social-035": { sentence: "你去接人，我去攞票。", sentence_jyutping: "nei5 heoi3 zip3 jan4, ngo5 heoi3 lo2 piu3.", sentence_mandarin: "你去接人，我去拿票。" },
  "social-036": { sentence: "放飛機咁多次，算數啦。", sentence_jyutping: "fong3 fei1 gei1 gam3 do1 ci3, syun3 sou3 laa1.", sentence_mandarin: "放鸽子这么多次，算了吧。" },
  "social-037": { sentence: "準時到先係有交帶。", sentence_jyutping: "zeon2 si4 dou3 sin1 hai6 jau5 gaau1 daai3.", sentence_mandarin: "准时到才算有交代。" },
  "social-038": { sentence: "見面先講，電話講唔清。", sentence_jyutping: "gin3 min6 sin1 gong2, din6 waa2 gong2 m4 cing1.", sentence_mandarin: "见面再说，电话里讲不清。" },
  "social-039": { sentence: "傾計傾到唔知時間。", sentence_jyutping: "king1 gai3 king1 dou3 m4 zi1 si4 gaan3.", sentence_mandarin: "聊天聊到忘了时间。" },
  "social-040": { sentence: "放工去吹水，減壓一流。", sentence_jyutping: "fong3 gung1 heoi3 ceoi1 seoi2, gaam2 aat3 jat1 lau4.", sentence_mandarin: "下班去吹水，解压一流。" },
  "social-041": { sentence: "自拍角度搵啱先好睇。", sentence_jyutping: "zi6 paak3 gok3 dou6 wan2 ngaam1 sin1 hou2 tai2.", sentence_mandarin: "自拍角度找对了才好看。" },
  "social-042": { sentence: "群組通知又爆晒，睇唔切。", sentence_jyutping: "kwan4 zou2 tung1 zi1 jau6 baau3 saai3, tai2 m4 cit3.", sentence_mandarin: "群组通知又爆了，根本看不完。" },
  "social-043": { sentence: "加好友之前，睇下係邊個。", sentence_jyutping: "gaa1 hou2 jau5 zi1 cin4, tai2 haa5 hai6 bin1 go3.", sentence_mandarin: "加好友前，先看看是谁。" },
  "social-044": { sentence: "有咩事就私訊我啦。", sentence_jyutping: "jau5 me1 si6 zau6 si1 seon3 ngo5 laa1.", sentence_mandarin: "有事就私信我吧。" },
  "social-045": { sentence: "見到靚相記得點讚呀。", sentence_jyutping: "gin3 dou2 leng3 soeng2 gei3 dak1 dim2 zaan3 aa3.", sentence_mandarin: "看到好照片记得点赞哦。" },
  "social-046": { sentence: "留言唔使長，重點就得。", sentence_jyutping: "lau4 jin4 m4 sai2 coeng4, zung6 dim2 zau6 dak1.", sentence_mandarin: "留言不用长，重点就行。" },
  "social-047": { sentence: "今晚約飯，邊間你話事。", sentence_jyutping: "gam1 maan5 joek3 faan6, bin1 gaan1 nei5 waa6 si6.", sentence_mandarin: "今晚约饭，哪家你来定。" },
  "social-048": { sentence: "約會咪遲到，印象好緊要。", sentence_jyutping: "joek3 wui2 mai6 ci4 dou3, jan3 zoeng6 hou2 gan2 jiu3.", sentence_mandarin: "约会别迟到，第一印象很重要。" },
  "social-049": { sentence: "食完飯去海旁散步啦。", sentence_jyutping: "sik6 jyun4 faan6 heoi3 hoi2 pong4 saan3 bou6 laa1.", sentence_mandarin: "吃完饭去海边散步吧。" },
  "social-050": { sentence: "朝早跑步，成日都醒神。", sentence_jyutping: "ziu1 zou2 paau2 bou6, seng4 jat6 dou1 seng2 san4.", sentence_mandarin: "早上跑步，一整天都精神。" },
  "social-051": { sentence: "週末去郊游，吸下新鮮氣。", sentence_jyutping: "zau1 mut6 heoi3 gaau1 jau4, kap1 haa5 san1 sin1 hei3.", sentence_mandarin: "周末去郊游，吸点新鲜空气。" },
  "social-052": { sentence: "今期睇展幾有驚喜喎。", sentence_jyutping: "gam1 kei4 tai2 zin2 gei2 jau5 ging1 hei2 wo3.", sentence_mandarin: "这期看展还挺有惊喜。" },
  "social-053": { sentence: "睇演唱會要早啲入場。", sentence_jyutping: "tai2 jin2 coeng3 wui2 jiu3 zou2 di1 jap6 coeng4.", sentence_mandarin: "看演唱会要早点进场。" },
  "social-054": { sentence: "夜蒲還夜蒲，唔好過火。", sentence_jyutping: "je6 pou4 waan4 je6 pou4, m4 hou2 gwo3 fo2.", sentence_mandarin: "夜生活归夜生活，别玩太过。" },
  "social-055": { sentence: "太夜喇，返屋企先講。", sentence_jyutping: "taai3 je6 laa3, faan1 uk1 kei2 sin1 gong2.", sentence_mandarin: "太晚了，先回家再说。" },
  "social-056": { sentence: "你快啲過嚟，等緊你呀。", sentence_jyutping: "nei5 faai3 di1 gwo3 lai4, dang2 gan2 nei5 aa3.", sentence_mandarin: "你快点过来，大家等你呢。" },
  "social-057": { sentence: "搭順風車記得分油錢。", sentence_jyutping: "daap3 seon6 fung1 ce1 gei3 dak1 fan1 jau4 cin2.", sentence_mandarin: "搭顺风车记得分摊油钱。" },
  "social-058": { sentence: "過馬路睇清楚先行。", sentence_jyutping: "gwo3 maa5 lou6 tai2 cing1 co2 sin1 haang4.", sentence_mandarin: "过马路先看清楚再走。" },
  "social-059": { sentence: "轉線要快，唔係趕唔切。", sentence_jyutping: "zyun2 sin3 jiu3 faai3, m4 hai6 gon2 m4 cit3.", sentence_mandarin: "换线要快，不然赶不上。" },
  "social-060": { sentence: "等車等到瞓著咗喇。", sentence_jyutping: "dang2 ce1 dang2 dou3 fan3 zoek6 zo2 laa3.", sentence_mandarin: "等车等到都快睡着了。" },
  "emotion-001": { sentence: "聽到好消息，真係好開心。", sentence_jyutping: "teng1 dou2 hou2 siu1 sik1, zan1 hai6 hou2 hoi1 sam1.", sentence_mandarin: "听到好消息，真的很开心。" },
  "emotion-002": { sentence: "搞咗成日都唔掂，唔開心。", sentence_jyutping: "gaau2 zo2 seng4 jat6 dou1 m4 dim6, m4 hoi1 sam1.", sentence_mandarin: "忙了一天还是不顺，心情很差。" },
  "emotion-003": { sentence: "佢咁講真係激氣到震。", sentence_jyutping: "keoi5 gam3 gong2 zan1 hai6 gik1 hei3 dou3 zan3.", sentence_mandarin: "他这样说真是气到发抖。" },
  "emotion-004": { sentence: "地鐵又壞，搞到好煩躁。", sentence_jyutping: "dei6 tit3 jau6 waai6, gaau2 dou3 hou2 faan4 cou3.", sentence_mandarin: "地铁又坏了，搞得人很烦躁。" },
  "emotion-005": { sentence: "你今次真係好犀利喎！", sentence_jyutping: "nei5 gam1 ci3 zan1 hai6 hou2 sai1 lei6 wo3!", sentence_mandarin: "你这次真的太厉害了！" },
  "emotion-006": { sentence: "上台前有啲緊張正常。", sentence_jyutping: "soeng5 toi4 cin4 jau5 di1 gan2 zoeng1 zing3 soeng4.", sentence_mandarin: "上台前有点紧张很正常。" },
  "emotion-007": { sentence: "深呼吸兩下，放鬆啲啦。", sentence_jyutping: "sam1 fu1 kap1 loeng5 haa5, fong3 sung1 di1 laa1.", sentence_mandarin: "深呼吸两下，放松一点。" },
  "emotion-008": { sentence: "仲未覆機，真係擔心。", sentence_jyutping: "zung6 mei6 fuk1 gei1, zan1 hai6 daam1 sam1.", sentence_mandarin: "还没回消息，真的担心。" },
  "emotion-009": { sentence: "放心啦，呢單我睇住。", sentence_jyutping: "fong3 sam1 laa1, ni1 daan1 ngo5 tai2 zyu6.", sentence_mandarin: "放心吧，这件事我盯着。" },
  "emotion-010": { sentence: "突然黑燈，成班人都驚。", sentence_jyutping: "dat6 jin4 hak1 dang1, seng4 baan1 jan4 dou1 geng1.", sentence_mandarin: "突然停电，大家都被吓到了。" },
  "emotion-011": { sentence: "見工前驚青都好合理。", sentence_jyutping: "gin3 gung1 cin4 geng1 ceng1 dou1 hou2 hap6 lei5.", sentence_mandarin: "面试前慌张其实很正常。" },
  "emotion-012": { sentence: "唔好再嬲，飲杯水先。", sentence_jyutping: "m4 hou2 zoi3 nau1, jam2 bui1 seoi2 sin1.", sentence_mandarin: "别再生气了，先喝口水。" },
  "emotion-013": { sentence: "有時真係無奈到笑。", sentence_jyutping: "jau5 si4 zan1 hai6 mou4 noi6 dou3 siu3.", sentence_mandarin: "有时候真是无奈到想笑。" },
  "emotion-014": { sentence: "喺電梯撞正前度，好尷尬。", sentence_jyutping: "hai2 din6 tai1 zong6 zing3 cin4 dou6, hou2 gaam3 gaai3.", sentence_mandarin: "在电梯碰到前任，太尴尬了。" },
  "emotion-015": { sentence: "等咗咁耐都冇位，好失望。", sentence_jyutping: "dang2 zo2 gam3 noi6 dou1 mou5 wai2, hou2 sat1 mong6.", sentence_mandarin: "等了这么久还是没位，挺失望的。" },
  "emotion-016": { sentence: "聽到佢句說話真係感動。", sentence_jyutping: "teng1 dou2 keoi5 geoi3 syut3 waa6 zan1 hai6 gam2 dung6.", sentence_mandarin: "听到他说那句话真的很感动。" },
  "emotion-017": { sentence: "今日好滿足，食到心頭好。", sentence_jyutping: "gam1 jat6 hou2 mun5 zuk1, sik6 dou3 sam1 tau4 hou2.", sentence_mandarin: "今天很满足，吃到了心头好。" },
  "emotion-018": { sentence: "一家人齊齊整整最幸福。", sentence_jyutping: "jat1 gaa1 jan4 cai4 cai4 zing2 zing2 zeoi3 hang6 fuk1.", sentence_mandarin: "一家人整整齐齐最幸福。" },
  "emotion-019": { sentence: "多謝你幫手，真係感激。", sentence_jyutping: "do1 ze6 nei5 bong1 sau2, zan1 hai6 gam2 gik1.", sentence_mandarin: "谢谢你帮忙，我真的很感激。" },
  "emotion-020": { sentence: "講錯嘢，心入面好內疚。", sentence_jyutping: "gong2 co3 je5, sam1 jap6 min6 hou2 noi6 gau3.", sentence_mandarin: "说错话了，心里很内疚。" },
  "emotion-021": { sentence: "早知咁樣，真係會後悔。", sentence_jyutping: "zou2 zi1 gam3 joeng6, zan1 hai6 wui5 hau6 fui3.", sentence_mandarin: "早知道这样，真的会后悔。" },
  "emotion-022": { sentence: "佢攞獎嗰刻，我好自豪。", sentence_jyutping: "keoi5 lo2 zoeng2 go2 hak1, ngo5 hou2 zi6 hou4.", sentence_mandarin: "他领奖那一刻，我很自豪。" },
  "emotion-023": { sentence: "Deadline壓力大到瞓唔着。", sentence_jyutping: "ded1 lai1 aat3 lik6 daai6 dou3 fan3 m4 zoek6.", sentence_mandarin: "deadline压力大到睡不着。" },
  "emotion-024": { sentence: "一次過爆單，成個人崩潰。", sentence_jyutping: "jat1 ci3 gwo3 baau3 daan1, seng4 go3 jan4 bang1 kui2.", sentence_mandarin: "一下子爆单，整个人都崩溃了。" },
  "emotion-025": { sentence: "先坐低，冷靜咗再講。", sentence_jyutping: "sin1 co5 dai1, laang5 zing6 zo2 zoi3 gong2.", sentence_mandarin: "先坐下，冷静了再说。" },
  "emotion-026": { sentence: "唔好咁衝動，諗清楚先。", sentence_jyutping: "m4 hou2 gam3 cung1 dung6, nam2 cing1 co2 sin1.", sentence_mandarin: "别这么冲动，先想清楚。" },
  "emotion-027": { sentence: "重複聽同一句，真係厭煩。", sentence_jyutping: "cung4 fuk1 teng1 tung4 jat1 geoi3, zan1 hai6 jim3 faan4.", sentence_mandarin: "同一句反复听，真的很烦。" },
  "emotion-028": { sentence: "好期待下個月去旅行。", sentence_jyutping: "hou2 kei4 doi6 haa6 go3 jyut6 heoi3 leoi5 hang4.", sentence_mandarin: "很期待下个月去旅行。" },
  "emotion-029": { sentence: "中獎嗰下，興奮到跳起。", sentence_jyutping: "zung3 zoeng2 go2 haa5, hing1 fan5 dou3 tiu3 hei2.", sentence_mandarin: "中奖那一下，兴奋到跳起来。" },
  "emotion-030": { sentence: "專心做，唔好再睇電話。", sentence_jyutping: "zyun1 sam1 zou6, m4 hou2 zoi3 tai2 din6 waa2.", sentence_mandarin: "专心做事，别再看手机。" },
  "emotion-031": { sentence: "心散晒，做嘢成日分心。", sentence_jyutping: "sam1 saan3 saai3, zou6 je5 seng4 jat6 fan1 sam1.", sentence_mandarin: "心都散了，做事老分心。" },
  "emotion-032": { sentence: "成個下晝都無聊到極。", sentence_jyutping: "seng4 go3 haa6 zau3 dou1 mou4 liu4 dou3 gik6.", sentence_mandarin: "整个下午都无聊透顶。" },
  "emotion-033": { sentence: "悶到發慌，不如出去行。", sentence_jyutping: "mun6 dou3 faat3 fong1, bat1 jyu4 ceot1 heoi3 haang4.", sentence_mandarin: "闷到发慌，不如出去走走。" },
  "emotion-034": { sentence: "瞓夠先有精神開工。", sentence_jyutping: "fan3 gau3 sin1 jau5 zing1 san4 hoi1 gung1.", sentence_mandarin: "睡够了才有精神开工。" },
  "emotion-035": { sentence: "連續開會，真係好疲倦。", sentence_jyutping: "lin4 zuk6 hoi1 wui6, zan1 hai6 hou2 pei4 gyun6.", sentence_mandarin: "连续开会，真的很疲惫。" },
  "emotion-036": { sentence: "眼瞓到死，飲咖啡都唔掂。", sentence_jyutping: "ngaan5 fan3 dou3 sei2, jam2 gaa3 fe1 dou1 m4 dim6.", sentence_mandarin: "困到不行，喝咖啡都顶不住。" },
  "emotion-037": { sentence: "肚餓喇，邊度有嘢食？", sentence_jyutping: "tou5 ngo6 laa3, bin1 dou6 jau5 je5 sik6?", sentence_mandarin: "肚子饿了，哪里有吃的？" },
  "emotion-038": { sentence: "口渴到爆，快啲買水。", sentence_jyutping: "hau2 hot3 dou3 baau3, faai3 di1 maai5 seoi2.", sentence_mandarin: "渴到不行，快去买水。" },
  "emotion-039": { sentence: "唔使心急，慢慢嚟得㗎。", sentence_jyutping: "m4 sai2 sam1 gap1, maan6 maan6 lai4 dak1 gaa3.", sentence_mandarin: "不用着急，慢慢来就行。" },
  "emotion-040": { sentence: "你咁淡定，真係佩服。", sentence_jyutping: "nei5 gam3 daam6 ding6, zan1 hai6 pui3 fuk6.", sentence_mandarin: "你这么淡定，真服你。" },
  "emotion-041": { sentence: "諗極都唔掂，心入面掙扎。", sentence_jyutping: "nam2 gik6 dou1 m4 dim6, sam1 jap6 min6 zang1 zaat3.", sentence_mandarin: "怎么想都拿不定，心里很挣扎。" },
  "emotion-042": { sentence: "睇返舊相，突然有感慨。", sentence_jyutping: "tai2 faan1 gau6 soeng2, dat6 jin4 jau5 gam2 koi2.", sentence_mandarin: "翻看旧照，忽然很感慨。" },
  "emotion-043": { sentence: "你講到我一頭霧水，好疑惑。", sentence_jyutping: "nei5 gong2 dou3 ngo5 jat1 tau4 mou6 seoi2, hou2 ji4 waak6.", sentence_mandarin: "你说得我一头雾水，很疑惑。" },
  "emotion-044": { sentence: "你處理得咁靚，真係佩服。", sentence_jyutping: "nei5 cyu2 lei5 dak1 gam3 leng3, zan1 hai6 pui3 fuk6.", sentence_mandarin: "你处理得这么漂亮，真佩服。" },
  "emotion-045": { sentence: "見到佢升職，心入面有啲妒忌。", sentence_jyutping: "gin3 dou2 keoi5 sing1 zik1, sam1 jap6 min6 jau5 di1 dou3 gei6.", sentence_mandarin: "看他升职，心里有点嫉妒。" },
  "emotion-046": { sentence: "做錯咗仲嘴硬，真羞愧。", sentence_jyutping: "zou6 co3 zo2 zung6 zeoi2 ngaang6, zan1 sau1 kwai5.", sentence_mandarin: "做错了还嘴硬，真羞愧。" },
  "emotion-047": { sentence: "有你喺度，我先安心。", sentence_jyutping: "jau5 nei5 hai2 dou6, ngo5 sin1 on1 sam1.", sentence_mandarin: "有你在，我才安心。" },
  "emotion-048": { sentence: "全場倒數嗰陣超激動。", sentence_jyutping: "cyun4 coeng4 dou3 sou3 go2 zan6 ciu1 gik1 dung6.", sentence_mandarin: "全场倒数那一刻超级激动。" },
  "emotion-049": { sentence: "講到火都嚟，真係火滾。", sentence_jyutping: "gong2 dou3 fo2 dou1 lai4, zan1 hai6 fo2 gwan2.", sentence_mandarin: "讲到火都上来，真的很火大。" },
  "emotion-050": { sentence: "成日等人，等到冇癮。", sentence_jyutping: "seng4 jat6 dang2 jan4, dang2 dou3 mou5 jan2.", sentence_mandarin: "老是等人，等到没劲。" },
  "emotion-051": { sentence: "呢件事我真係好上心。", sentence_jyutping: "ni1 gin6 si6 ngo5 zan1 hai6 hou2 soeng5 sam1.", sentence_mandarin: "这件事我真的很上心。" },
  "emotion-052": { sentence: "連輸幾鋪，灰心都正常。", sentence_jyutping: "lin4 syu1 gei2 pou3, fui1 sam1 dou1 zing3 soeng4.", sentence_mandarin: "连输几把，灰心也正常。" },
  "emotion-053": { sentence: "有信心啦，你一定得。", sentence_jyutping: "jau5 seon3 sam1 laa1, nei5 jat1 ding6 dak1.", sentence_mandarin: "有点信心，你一定行。" },
  "emotion-054": { sentence: "咁樂觀，難怪你瞓得着。", sentence_jyutping: "gam3 lok6 gun1, naan4 gwaai3 nei5 fan3 dak1 zoek6.", sentence_mandarin: "这么乐观，难怪你睡得着。" },
  "emotion-055": { sentence: "成件事睇落好悲觀喎。", sentence_jyutping: "seng4 gin6 si6 tai2 lok6 hou2 bei1 gun1 wo3.", sentence_mandarin: "整件事看起来挺悲观的。" },
  "emotion-056": { sentence: "求助無門，真係好無助。", sentence_jyutping: "kau4 zo6 mou4 mun4, zan1 hai6 hou2 mou4 zo6.", sentence_mandarin: "求助无门，真的很无助。" },
  "emotion-057": { sentence: "講開咗就釋懷好多。", sentence_jyutping: "gong2 hoi1 zo2 zau6 sik1 waai4 hou2 do1.", sentence_mandarin: "讲开之后，心里轻松很多。" },
  "emotion-058": { sentence: "沖完涼即刻舒服晒。", sentence_jyutping: "cung1 jyun4 loeng4 zik1 hak1 syu1 fuk6 saai3.", sentence_mandarin: "洗完澡立刻舒服多了。" },
  "emotion-059": { sentence: "頭暈又作悶，真係唔舒服。", sentence_jyutping: "tau4 wan4 jau6 zok3 mun6, zan1 hai6 m4 syu1 fuk6.", sentence_mandarin: "头晕又反胃，真的不舒服。" },
  "emotion-060": { sentence: "呢趟旅行真係好治癒。", sentence_jyutping: "ni1 tong3 leoi5 hang4 zan1 hai6 hou2 zi6 jyu6.", sentence_mandarin: "这趟旅行真的很治愈。" },
};

const EXTRA_60_SENTENCE_MANDARIN: Record<string, string> = {
  "foodhk-001": "麻烦，这边结账。",
  "foodhk-002": "今天加个菜，还有蒸鱼。",
  "foodhk-003": "这盘帮我快火翻热一下。",
  "foodhk-004": "我要一碗河粉，不要葱。",
  "foodhk-005": "早上吃碗小份云吞面就够了。",
  "foodhk-006": "多士记得把底烘脆。",
  "foodhk-007": "今晚去吃打冷当宵夜。",
  "foodhk-008": "楼下两餸饭便宜又快。",
  "foodhk-009": "我们在茶记等你。",
  "foodhk-010": "我要一杯飞沙走奶。",
  "foodhk-011": "天气热，喝冰柠茶最对味。",
  "foodhk-012": "他最爱喝冻柠乐。",
  "foodhk-013": "午餐我喝冰鸳鸯。",
  "foodhk-014": "下雨天喝热鸳鸯特别舒服。",
  "foodhk-015": "奶酱多要趁热吃。",
  "foodhk-016": "早餐先来一份蛋治。",
  "foodhk-017": "我点了一份腿蛋治。",
  "foodhk-018": "宵夜吃餐蛋面最省事。",
  "foodhk-019": "这家茶记的沙嗲牛肉面很有名。",
  "foodhk-020": "这家店的干炒牛河镬气很足。",
  "foodhk-021": "豉油皇炒面够香口。",
  "foodhk-022": "早上吃艇仔粥很暖胃。",
  "foodhk-023": "我爸最爱及第粥。",
  "foodhk-024": "今天例汤是老火汤。",
  "foodhk-025": "妈煲的老火汤特别清甜。",
  "foodhk-026": "吃饭记得点一碟白灼菜。",
  "foodhk-027": "今晚吃椒盐鲜鱿。",
  "foodhk-028": "他们最拿手就是避风塘炒蟹。",
  "foodhk-029": "冬天吃煲仔饭最过瘾。",
  "foodhk-030": "饭后吃一件糖不甩。",
  "colloq-001": "你再吵就闭嘴。",
  "colloq-002": "一听到这个消息我立刻泄气了。",
  "colloq-003": "他说话总是莫名其妙。",
  "colloq-004": "这次真的出大事了。",
  "colloq-005": "这份文件我已经搞定了。",
  "colloq-006": "这个价钱真是离谱。",
  "colloq-007": "你在说什么，太离谱了吧。",
  "colloq-008": "这场球踢得我都看不下去。",
  "colloq-009": "这台机器还是不行。",
  "colloq-010": "今天做事顺到不行。",
  "colloq-011": "吃什么都行，随便啦。",
  "colloq-012": "他做事太随便了。",
  "colloq-013": "你们现在到底什么情况？",
  "colloq-014": "你这么晚还不睡，干嘛呢？",
  "colloq-015": "你想吃什么？",
  "colloq-016": "不是吧，这样也行？",
  "colloq-017": "你刚刚真的把我吓到了。",
  "colloq-018": "这天气热得我受不了。",
  "colloq-019": "这家店的烧味真的很绝。",
  "colloq-020": "整晚坐着发呆，太没劲了。",
  "colloq-021": "都做到这步了，不差那一点。",
  "colloq-022": "我无所谓，你来决定吧。",
  "colloq-023": "他说得我火都上来了。",
  "colloq-024": "真是气死我了。",
  "colloq-025": "别装聪明了。",
  "colloq-026": "他整天装模作样。",
  "colloq-027": "我们坐着围观吃瓜就好。",
  "colloq-028": "下班一起去吹水吧。",
  "colloq-029": "这次只能硬着头皮吞下去。",
  "colloq-030": "这事得看情况再决定。",
};

export const PRACTICE_VOCAB: PracticeVocab[] = [
  ...makeCategoryEntries(WORK_RAW, "职场工作", "work"),
  ...makeCategoryEntries(FOOD_RAW, "饮食文化", "food"),
  ...makeCategoryEntries(SOCIAL_RAW, "交通与社交", "social"),
  ...makeCategoryEntries(EMOTION_RAW, "生活情绪", "emotion"),
  ...makeSentenceEntries(FOOD_HK_EXTRA_RAW, "饮食文化", "foodhk"),
  ...makeSentenceEntries(COLLOQ_EXTRA_RAW, "地道口语", "colloq"),
].map((item) => {
  const override = FIRST_BATCH_OVERRIDES[item.id];
  const mandarinOverride = EXTRA_60_SENTENCE_MANDARIN[item.id];

  if (override) {
    return {
      ...item,
      sentence: override.sentence,
      sentence_jyutping: override.sentence_jyutping,
      sentence_mandarin: override.sentence_mandarin,
      sentence_pinyin: override.sentence_jyutping,
    };
  }

  if (mandarinOverride) {
    return {
      ...item,
      sentence_mandarin: mandarinOverride,
    };
  }

  return item;
});
